var annotated_dup =
[
    [ "roc", "namespaceroc.html", [
      [ "address", "namespaceroc_1_1address.html", [
        [ "EndpointUri", "classroc_1_1address_1_1EndpointUri.html", "classroc_1_1address_1_1EndpointUri" ],
        [ "endpoint_uri_to_str", "classroc_1_1address_1_1endpoint__uri__to__str.html", "classroc_1_1address_1_1endpoint__uri__to__str" ],
        [ "IoUri", "classroc_1_1address_1_1IoUri.html", "classroc_1_1address_1_1IoUri" ],
        [ "io_uri_to_str", "classroc_1_1address_1_1io__uri__to__str.html", "classroc_1_1address_1_1io__uri__to__str" ],
        [ "ProtocolAttrs", "structroc_1_1address_1_1ProtocolAttrs.html", "structroc_1_1address_1_1ProtocolAttrs" ],
        [ "ProtocolMap", "classroc_1_1address_1_1ProtocolMap.html", "classroc_1_1address_1_1ProtocolMap" ],
        [ "socket_addr_to_str", "classroc_1_1address_1_1socket__addr__to__str.html", "classroc_1_1address_1_1socket__addr__to__str" ],
        [ "SocketAddr", "classroc_1_1address_1_1SocketAddr.html", "classroc_1_1address_1_1SocketAddr" ]
      ] ],
      [ "audio", "namespaceroc_1_1audio.html", [
        [ "BuiltinResampler", "classroc_1_1audio_1_1BuiltinResampler.html", "classroc_1_1audio_1_1BuiltinResampler" ],
        [ "ChannelMapper", "classroc_1_1audio_1_1ChannelMapper.html", "classroc_1_1audio_1_1ChannelMapper" ],
        [ "ChannelMapperMatrix", "classroc_1_1audio_1_1ChannelMapperMatrix.html", "classroc_1_1audio_1_1ChannelMapperMatrix" ],
        [ "ChannelMapperReader", "classroc_1_1audio_1_1ChannelMapperReader.html", "classroc_1_1audio_1_1ChannelMapperReader" ],
        [ "ChannelMapRule", "structroc_1_1audio_1_1ChannelMapRule.html", "structroc_1_1audio_1_1ChannelMapRule" ],
        [ "ChannelMap", "structroc_1_1audio_1_1ChannelMap.html", "structroc_1_1audio_1_1ChannelMap" ],
        [ "ChannelList", "structroc_1_1audio_1_1ChannelList.html", "structroc_1_1audio_1_1ChannelList" ],
        [ "ChannelMapperWriter", "classroc_1_1audio_1_1ChannelMapperWriter.html", "classroc_1_1audio_1_1ChannelMapperWriter" ],
        [ "ChannelSet", "classroc_1_1audio_1_1ChannelSet.html", "classroc_1_1audio_1_1ChannelSet" ],
        [ "channel_set_to_str", "classroc_1_1audio_1_1channel__set__to__str.html", "classroc_1_1audio_1_1channel__set__to__str" ],
        [ "DecimationResampler", "classroc_1_1audio_1_1DecimationResampler.html", "classroc_1_1audio_1_1DecimationResampler" ],
        [ "Depacketizer", "classroc_1_1audio_1_1Depacketizer.html", "classroc_1_1audio_1_1Depacketizer" ],
        [ "Fanout", "classroc_1_1audio_1_1Fanout.html", "classroc_1_1audio_1_1Fanout" ],
        [ "Frame", "classroc_1_1audio_1_1Frame.html", "classroc_1_1audio_1_1Frame" ],
        [ "FreqEstimatorConfig", "structroc_1_1audio_1_1FreqEstimatorConfig.html", "structroc_1_1audio_1_1FreqEstimatorConfig" ],
        [ "FreqEstimator", "classroc_1_1audio_1_1FreqEstimator.html", "classroc_1_1audio_1_1FreqEstimator" ],
        [ "IFrameDecoder", "classroc_1_1audio_1_1IFrameDecoder.html", "classroc_1_1audio_1_1IFrameDecoder" ],
        [ "IFrameEncoder", "classroc_1_1audio_1_1IFrameEncoder.html", "classroc_1_1audio_1_1IFrameEncoder" ],
        [ "IFrameReader", "classroc_1_1audio_1_1IFrameReader.html", "classroc_1_1audio_1_1IFrameReader" ],
        [ "IFrameWriter", "classroc_1_1audio_1_1IFrameWriter.html", "classroc_1_1audio_1_1IFrameWriter" ],
        [ "IResampler", "classroc_1_1audio_1_1IResampler.html", "classroc_1_1audio_1_1IResampler" ],
        [ "LatencyMonitorConfig", "structroc_1_1audio_1_1LatencyMonitorConfig.html", "structroc_1_1audio_1_1LatencyMonitorConfig" ],
        [ "LatencyMonitorMetrics", "structroc_1_1audio_1_1LatencyMonitorMetrics.html", "structroc_1_1audio_1_1LatencyMonitorMetrics" ],
        [ "LatencyMonitor", "classroc_1_1audio_1_1LatencyMonitor.html", "classroc_1_1audio_1_1LatencyMonitor" ],
        [ "Mixer", "classroc_1_1audio_1_1Mixer.html", "classroc_1_1audio_1_1Mixer" ],
        [ "NullWriter", "classroc_1_1audio_1_1NullWriter.html", "classroc_1_1audio_1_1NullWriter" ],
        [ "Packetizer", "classroc_1_1audio_1_1Packetizer.html", "classroc_1_1audio_1_1Packetizer" ],
        [ "PcmDecoder", "classroc_1_1audio_1_1PcmDecoder.html", "classroc_1_1audio_1_1PcmDecoder" ],
        [ "PcmEncoder", "classroc_1_1audio_1_1PcmEncoder.html", "classroc_1_1audio_1_1PcmEncoder" ],
        [ "PcmFormat", "structroc_1_1audio_1_1PcmFormat.html", "structroc_1_1audio_1_1PcmFormat" ],
        [ "PcmTraits", "structroc_1_1audio_1_1PcmTraits.html", "structroc_1_1audio_1_1PcmTraits" ],
        [ "PcmMapper", "classroc_1_1audio_1_1PcmMapper.html", "classroc_1_1audio_1_1PcmMapper" ],
        [ "PoisonReader", "classroc_1_1audio_1_1PoisonReader.html", "classroc_1_1audio_1_1PoisonReader" ],
        [ "ProfilerConfig", "structroc_1_1audio_1_1ProfilerConfig.html", "structroc_1_1audio_1_1ProfilerConfig" ],
        [ "Profiler", "classroc_1_1audio_1_1Profiler.html", "classroc_1_1audio_1_1Profiler" ],
        [ "ProfilingReader", "classroc_1_1audio_1_1ProfilingReader.html", "classroc_1_1audio_1_1ProfilingReader" ],
        [ "ProfilingWriter", "classroc_1_1audio_1_1ProfilingWriter.html", "classroc_1_1audio_1_1ProfilingWriter" ],
        [ "ResamplerMap", "classroc_1_1audio_1_1ResamplerMap.html", "classroc_1_1audio_1_1ResamplerMap" ],
        [ "ResamplerReader", "classroc_1_1audio_1_1ResamplerReader.html", "classroc_1_1audio_1_1ResamplerReader" ],
        [ "ResamplerWriter", "classroc_1_1audio_1_1ResamplerWriter.html", "classroc_1_1audio_1_1ResamplerWriter" ],
        [ "SampleSpec", "classroc_1_1audio_1_1SampleSpec.html", "classroc_1_1audio_1_1SampleSpec" ],
        [ "sample_spec_to_str", "classroc_1_1audio_1_1sample__spec__to__str.html", "classroc_1_1audio_1_1sample__spec__to__str" ],
        [ "SpeexResampler", "classroc_1_1audio_1_1SpeexResampler.html", "classroc_1_1audio_1_1SpeexResampler" ],
        [ "WatchdogConfig", "structroc_1_1audio_1_1WatchdogConfig.html", "structroc_1_1audio_1_1WatchdogConfig" ],
        [ "Watchdog", "classroc_1_1audio_1_1Watchdog.html", "classroc_1_1audio_1_1Watchdog" ]
      ] ],
      [ "core", "namespaceroc_1_1core.html", [
        [ "AlignMax", "unionroc_1_1core_1_1AlignMax.html", "unionroc_1_1core_1_1AlignMax" ],
        [ "AlignOps", "classroc_1_1core_1_1AlignOps.html", null ],
        [ "AlignedStorage", "classroc_1_1core_1_1AlignedStorage.html", "classroc_1_1core_1_1AlignedStorage" ],
        [ "ArenaAllocation", "classroc_1_1core_1_1ArenaAllocation.html", "classroc_1_1core_1_1ArenaAllocation" ],
        [ "PoolAllocation", "classroc_1_1core_1_1PoolAllocation.html", "classroc_1_1core_1_1PoolAllocation" ],
        [ "CustomAllocation", "classroc_1_1core_1_1CustomAllocation.html", "classroc_1_1core_1_1CustomAllocation" ],
        [ "ManualAllocation", "classroc_1_1core_1_1ManualAllocation.html", "classroc_1_1core_1_1ManualAllocation" ],
        [ "Array", "classroc_1_1core_1_1Array.html", "classroc_1_1core_1_1Array" ],
        [ "Atomic", "classroc_1_1core_1_1Atomic.html", "classroc_1_1core_1_1Atomic" ],
        [ "Atomic< T * >", "classroc_1_1core_1_1Atomic_3_01T_01_5_01_4.html", "classroc_1_1core_1_1Atomic_3_01T_01_5_01_4" ],
        [ "Buffer", "classroc_1_1core_1_1Buffer.html", "classroc_1_1core_1_1Buffer" ],
        [ "BufferFactory", "classroc_1_1core_1_1BufferFactory.html", "classroc_1_1core_1_1BufferFactory" ],
        [ "EndianOps", "classroc_1_1core_1_1EndianOps.html", null ],
        [ "GlobalDestructor", "classroc_1_1core_1_1GlobalDestructor.html", "classroc_1_1core_1_1GlobalDestructor" ],
        [ "Hashmap", "classroc_1_1core_1_1Hashmap.html", "classroc_1_1core_1_1Hashmap" ],
        [ "HashmapImpl", "classroc_1_1core_1_1HashmapImpl.html", "classroc_1_1core_1_1HashmapImpl" ],
        [ "HashmapNode", "classroc_1_1core_1_1HashmapNode.html", "classroc_1_1core_1_1HashmapNode" ],
        [ "HeapArena", "classroc_1_1core_1_1HeapArena.html", "classroc_1_1core_1_1HeapArena" ],
        [ "IArena", "classroc_1_1core_1_1IArena.html", "classroc_1_1core_1_1IArena" ],
        [ "IPool", "classroc_1_1core_1_1IPool.html", "classroc_1_1core_1_1IPool" ],
        [ "List", "classroc_1_1core_1_1List.html", "classroc_1_1core_1_1List" ],
        [ "ListNode", "classroc_1_1core_1_1ListNode.html", "classroc_1_1core_1_1ListNode" ],
        [ "LogMessage", "structroc_1_1core_1_1LogMessage.html", "structroc_1_1core_1_1LogMessage" ],
        [ "Logger", "classroc_1_1core_1_1Logger.html", "classroc_1_1core_1_1Logger" ],
        [ "MemoryOps", "classroc_1_1core_1_1MemoryOps.html", null ],
        [ "MpscQueue", "classroc_1_1core_1_1MpscQueue.html", "classroc_1_1core_1_1MpscQueue" ],
        [ "MpscQueueImpl", "classroc_1_1core_1_1MpscQueueImpl.html", "classroc_1_1core_1_1MpscQueueImpl" ],
        [ "MpscQueueNode", "classroc_1_1core_1_1MpscQueueNode.html", "classroc_1_1core_1_1MpscQueueNode" ],
        [ "NonCopyable", "classroc_1_1core_1_1NonCopyable.html", "classroc_1_1core_1_1NonCopyable" ],
        [ "Optional", "classroc_1_1core_1_1Optional.html", "classroc_1_1core_1_1Optional" ],
        [ "SharedPtr", "classroc_1_1core_1_1SharedPtr.html", "classroc_1_1core_1_1SharedPtr" ],
        [ "RefCountedOwnership", "structroc_1_1core_1_1RefCountedOwnership.html", "structroc_1_1core_1_1RefCountedOwnership" ],
        [ "NoOwnership", "structroc_1_1core_1_1NoOwnership.html", "structroc_1_1core_1_1NoOwnership" ],
        [ "Printer", "classroc_1_1core_1_1Printer.html", "classroc_1_1core_1_1Printer" ],
        [ "RateLimiter", "classroc_1_1core_1_1RateLimiter.html", "classroc_1_1core_1_1RateLimiter" ],
        [ "RefCounted", "classroc_1_1core_1_1RefCounted.html", "classroc_1_1core_1_1RefCounted" ],
        [ "RefCountedImpl", "classroc_1_1core_1_1RefCountedImpl.html", "classroc_1_1core_1_1RefCountedImpl" ],
        [ "ScopedLock", "classroc_1_1core_1_1ScopedLock.html", "classroc_1_1core_1_1ScopedLock" ],
        [ "ScopedPtr", "classroc_1_1core_1_1ScopedPtr.html", "classroc_1_1core_1_1ScopedPtr" ],
        [ "Seqlock", "classroc_1_1core_1_1Seqlock.html", "classroc_1_1core_1_1Seqlock" ],
        [ "SlabPool", "classroc_1_1core_1_1SlabPool.html", "classroc_1_1core_1_1SlabPool" ],
        [ "SlabPoolImpl", "classroc_1_1core_1_1SlabPoolImpl.html", "classroc_1_1core_1_1SlabPoolImpl" ],
        [ "Slice", "classroc_1_1core_1_1Slice.html", "classroc_1_1core_1_1Slice" ],
        [ "StringBuffer", "classroc_1_1core_1_1StringBuffer.html", "classroc_1_1core_1_1StringBuffer" ],
        [ "StringBuilder", "classroc_1_1core_1_1StringBuilder.html", "classroc_1_1core_1_1StringBuilder" ],
        [ "StringList", "classroc_1_1core_1_1StringList.html", "classroc_1_1core_1_1StringList" ],
        [ "Console", "classroc_1_1core_1_1Console.html", "classroc_1_1core_1_1Console" ],
        [ "LogBackend", "classroc_1_1core_1_1LogBackend.html", "classroc_1_1core_1_1LogBackend" ],
        [ "AtomicOps", "classroc_1_1core_1_1AtomicOps.html", null ],
        [ "Semaphore", "classroc_1_1core_1_1Semaphore.html", "classroc_1_1core_1_1Semaphore" ],
        [ "Cond", "classroc_1_1core_1_1Cond.html", "classroc_1_1core_1_1Cond" ],
        [ "CrashHandler", "classroc_1_1core_1_1CrashHandler.html", "classroc_1_1core_1_1CrashHandler" ],
        [ "errno_to_str", "classroc_1_1core_1_1errno__to__str.html", "classroc_1_1core_1_1errno__to__str" ],
        [ "Mutex", "classroc_1_1core_1_1Mutex.html", "classroc_1_1core_1_1Mutex" ],
        [ "Singleton", "classroc_1_1core_1_1Singleton.html", null ],
        [ "TempFile", "classroc_1_1core_1_1TempFile.html", "classroc_1_1core_1_1TempFile" ],
        [ "Thread", "classroc_1_1core_1_1Thread.html", "classroc_1_1core_1_1Thread" ],
        [ "Ticker", "classroc_1_1core_1_1Ticker.html", "classroc_1_1core_1_1Ticker" ],
        [ "Timer", "classroc_1_1core_1_1Timer.html", "classroc_1_1core_1_1Timer" ]
      ] ],
      [ "ctl", "namespaceroc_1_1ctl.html", [
        [ "BasicControlEndpoint", "classroc_1_1ctl_1_1BasicControlEndpoint.html", "classroc_1_1ctl_1_1BasicControlEndpoint" ],
        [ "ControlInterfaceMap", "classroc_1_1ctl_1_1ControlInterfaceMap.html", "classroc_1_1ctl_1_1ControlInterfaceMap" ],
        [ "ControlLoop", "classroc_1_1ctl_1_1ControlLoop.html", "classroc_1_1ctl_1_1ControlLoop" ],
        [ "ControlTask", "classroc_1_1ctl_1_1ControlTask.html", "classroc_1_1ctl_1_1ControlTask" ],
        [ "IControlTaskExecutor", "classroc_1_1ctl_1_1IControlTaskExecutor.html", "classroc_1_1ctl_1_1IControlTaskExecutor" ],
        [ "ControlTaskExecutor", "classroc_1_1ctl_1_1ControlTaskExecutor.html", null ],
        [ "ControlTaskQueue", "classroc_1_1ctl_1_1ControlTaskQueue.html", "classroc_1_1ctl_1_1ControlTaskQueue" ],
        [ "IControlTaskCompleter", "classroc_1_1ctl_1_1IControlTaskCompleter.html", "classroc_1_1ctl_1_1IControlTaskCompleter" ]
      ] ],
      [ "fec", "namespaceroc_1_1fec.html", [
        [ "CodecConfig", "structroc_1_1fec_1_1CodecConfig.html", "structroc_1_1fec_1_1CodecConfig" ],
        [ "CodecMap", "classroc_1_1fec_1_1CodecMap.html", "classroc_1_1fec_1_1CodecMap" ],
        [ "Composer", "classroc_1_1fec_1_1Composer.html", "classroc_1_1fec_1_1Composer" ],
        [ "LDPC_Source_PayloadID", "classroc_1_1fec_1_1LDPC__Source__PayloadID.html", "classroc_1_1fec_1_1LDPC__Source__PayloadID" ],
        [ "LDPC_Repair_PayloadID", "classroc_1_1fec_1_1LDPC__Repair__PayloadID.html", "classroc_1_1fec_1_1LDPC__Repair__PayloadID" ],
        [ "RS8M_PayloadID", "classroc_1_1fec_1_1RS8M__PayloadID.html", "classroc_1_1fec_1_1RS8M__PayloadID" ],
        [ "IBlockDecoder", "classroc_1_1fec_1_1IBlockDecoder.html", "classroc_1_1fec_1_1IBlockDecoder" ],
        [ "IBlockEncoder", "classroc_1_1fec_1_1IBlockEncoder.html", "classroc_1_1fec_1_1IBlockEncoder" ],
        [ "Parser", "classroc_1_1fec_1_1Parser.html", "classroc_1_1fec_1_1Parser" ],
        [ "ReaderConfig", "structroc_1_1fec_1_1ReaderConfig.html", "structroc_1_1fec_1_1ReaderConfig" ],
        [ "Reader", "classroc_1_1fec_1_1Reader.html", "classroc_1_1fec_1_1Reader" ],
        [ "OpenfecDecoder", "classroc_1_1fec_1_1OpenfecDecoder.html", "classroc_1_1fec_1_1OpenfecDecoder" ],
        [ "OpenfecEncoder", "classroc_1_1fec_1_1OpenfecEncoder.html", "classroc_1_1fec_1_1OpenfecEncoder" ],
        [ "WriterConfig", "structroc_1_1fec_1_1WriterConfig.html", "structroc_1_1fec_1_1WriterConfig" ],
        [ "Writer", "classroc_1_1fec_1_1Writer.html", "classroc_1_1fec_1_1Writer" ]
      ] ],
      [ "netio", "namespaceroc_1_1netio.html", [
        [ "BasicPort", "classroc_1_1netio_1_1BasicPort.html", "classroc_1_1netio_1_1BasicPort" ],
        [ "ICloseHandler", "classroc_1_1netio_1_1ICloseHandler.html", "classroc_1_1netio_1_1ICloseHandler" ],
        [ "IConn", "classroc_1_1netio_1_1IConn.html", "classroc_1_1netio_1_1IConn" ],
        [ "IConnAcceptor", "classroc_1_1netio_1_1IConnAcceptor.html", "classroc_1_1netio_1_1IConnAcceptor" ],
        [ "IConnHandler", "classroc_1_1netio_1_1IConnHandler.html", "classroc_1_1netio_1_1IConnHandler" ],
        [ "INetworkTaskCompleter", "classroc_1_1netio_1_1INetworkTaskCompleter.html", "classroc_1_1netio_1_1INetworkTaskCompleter" ],
        [ "IResolverRequestHandler", "classroc_1_1netio_1_1IResolverRequestHandler.html", "classroc_1_1netio_1_1IResolverRequestHandler" ],
        [ "ITerminateHandler", "classroc_1_1netio_1_1ITerminateHandler.html", "classroc_1_1netio_1_1ITerminateHandler" ],
        [ "NetworkLoop", "classroc_1_1netio_1_1NetworkLoop.html", "classroc_1_1netio_1_1NetworkLoop" ],
        [ "NetworkTask", "classroc_1_1netio_1_1NetworkTask.html", "classroc_1_1netio_1_1NetworkTask" ],
        [ "Resolver", "classroc_1_1netio_1_1Resolver.html", "classroc_1_1netio_1_1Resolver" ],
        [ "ResolverRequest", "structroc_1_1netio_1_1ResolverRequest.html", "structroc_1_1netio_1_1ResolverRequest" ],
        [ "SocketOptions", "structroc_1_1netio_1_1SocketOptions.html", "structroc_1_1netio_1_1SocketOptions" ],
        [ "TcpConnectionConfig", "structroc_1_1netio_1_1TcpConnectionConfig.html", "structroc_1_1netio_1_1TcpConnectionConfig" ],
        [ "TcpClientConfig", "structroc_1_1netio_1_1TcpClientConfig.html", "structroc_1_1netio_1_1TcpClientConfig" ],
        [ "TcpConnectionPort", "classroc_1_1netio_1_1TcpConnectionPort.html", "classroc_1_1netio_1_1TcpConnectionPort" ],
        [ "TcpServerConfig", "structroc_1_1netio_1_1TcpServerConfig.html", "structroc_1_1netio_1_1TcpServerConfig" ],
        [ "TcpServerPort", "classroc_1_1netio_1_1TcpServerPort.html", "classroc_1_1netio_1_1TcpServerPort" ],
        [ "UdpReceiverConfig", "structroc_1_1netio_1_1UdpReceiverConfig.html", "structroc_1_1netio_1_1UdpReceiverConfig" ],
        [ "UdpReceiverPort", "classroc_1_1netio_1_1UdpReceiverPort.html", "classroc_1_1netio_1_1UdpReceiverPort" ],
        [ "UdpSenderConfig", "structroc_1_1netio_1_1UdpSenderConfig.html", "structroc_1_1netio_1_1UdpSenderConfig" ],
        [ "UdpSenderPort", "classroc_1_1netio_1_1UdpSenderPort.html", "classroc_1_1netio_1_1UdpSenderPort" ]
      ] ],
      [ "node", "namespaceroc_1_1node.html", [
        [ "ContextConfig", "structroc_1_1node_1_1ContextConfig.html", "structroc_1_1node_1_1ContextConfig" ],
        [ "Context", "classroc_1_1node_1_1Context.html", "classroc_1_1node_1_1Context" ],
        [ "Node", "classroc_1_1node_1_1Node.html", "classroc_1_1node_1_1Node" ],
        [ "Receiver", "classroc_1_1node_1_1Receiver.html", "classroc_1_1node_1_1Receiver" ],
        [ "ReceiverDecoder", "classroc_1_1node_1_1ReceiverDecoder.html", "classroc_1_1node_1_1ReceiverDecoder" ],
        [ "Sender", "classroc_1_1node_1_1Sender.html", "classroc_1_1node_1_1Sender" ],
        [ "SenderEncoder", "classroc_1_1node_1_1SenderEncoder.html", "classroc_1_1node_1_1SenderEncoder" ]
      ] ],
      [ "packet", "namespaceroc_1_1packet.html", [
        [ "ConcurrentQueue", "classroc_1_1packet_1_1ConcurrentQueue.html", "classroc_1_1packet_1_1ConcurrentQueue" ],
        [ "DelayedReader", "classroc_1_1packet_1_1DelayedReader.html", "classroc_1_1packet_1_1DelayedReader" ],
        [ "FEC", "structroc_1_1packet_1_1FEC.html", "structroc_1_1packet_1_1FEC" ],
        [ "IComposer", "classroc_1_1packet_1_1IComposer.html", "classroc_1_1packet_1_1IComposer" ],
        [ "Interleaver", "classroc_1_1packet_1_1Interleaver.html", "classroc_1_1packet_1_1Interleaver" ],
        [ "IParser", "classroc_1_1packet_1_1IParser.html", "classroc_1_1packet_1_1IParser" ],
        [ "IReader", "classroc_1_1packet_1_1IReader.html", "classroc_1_1packet_1_1IReader" ],
        [ "IWriter", "classroc_1_1packet_1_1IWriter.html", "classroc_1_1packet_1_1IWriter" ],
        [ "Packet", "classroc_1_1packet_1_1Packet.html", "classroc_1_1packet_1_1Packet" ],
        [ "PacketFactory", "classroc_1_1packet_1_1PacketFactory.html", "classroc_1_1packet_1_1PacketFactory" ],
        [ "Queue", "classroc_1_1packet_1_1Queue.html", "classroc_1_1packet_1_1Queue" ],
        [ "Router", "classroc_1_1packet_1_1Router.html", "classroc_1_1packet_1_1Router" ],
        [ "RTCP", "structroc_1_1packet_1_1RTCP.html", "structroc_1_1packet_1_1RTCP" ],
        [ "RTP", "structroc_1_1packet_1_1RTP.html", "structroc_1_1packet_1_1RTP" ],
        [ "Shipper", "classroc_1_1packet_1_1Shipper.html", "classroc_1_1packet_1_1Shipper" ],
        [ "SortedQueue", "classroc_1_1packet_1_1SortedQueue.html", "classroc_1_1packet_1_1SortedQueue" ],
        [ "UDP", "structroc_1_1packet_1_1UDP.html", "structroc_1_1packet_1_1UDP" ]
      ] ],
      [ "pipeline", "namespaceroc_1_1pipeline.html", [
        [ "TaskConfig", "structroc_1_1pipeline_1_1TaskConfig.html", "structroc_1_1pipeline_1_1TaskConfig" ],
        [ "SenderConfig", "structroc_1_1pipeline_1_1SenderConfig.html", "structroc_1_1pipeline_1_1SenderConfig" ],
        [ "ReceiverSessionConfig", "structroc_1_1pipeline_1_1ReceiverSessionConfig.html", "structroc_1_1pipeline_1_1ReceiverSessionConfig" ],
        [ "ReceiverCommonConfig", "structroc_1_1pipeline_1_1ReceiverCommonConfig.html", "structroc_1_1pipeline_1_1ReceiverCommonConfig" ],
        [ "ReceiverConfig", "structroc_1_1pipeline_1_1ReceiverConfig.html", "structroc_1_1pipeline_1_1ReceiverConfig" ],
        [ "TranscoderConfig", "structroc_1_1pipeline_1_1TranscoderConfig.html", "structroc_1_1pipeline_1_1TranscoderConfig" ],
        [ "IPipelineTaskCompleter", "classroc_1_1pipeline_1_1IPipelineTaskCompleter.html", "classroc_1_1pipeline_1_1IPipelineTaskCompleter" ],
        [ "IPipelineTaskScheduler", "classroc_1_1pipeline_1_1IPipelineTaskScheduler.html", "classroc_1_1pipeline_1_1IPipelineTaskScheduler" ],
        [ "SenderSessionMetrics", "structroc_1_1pipeline_1_1SenderSessionMetrics.html", "structroc_1_1pipeline_1_1SenderSessionMetrics" ],
        [ "SenderSlotMetrics", "structroc_1_1pipeline_1_1SenderSlotMetrics.html", "structroc_1_1pipeline_1_1SenderSlotMetrics" ],
        [ "ReceiverSessionMetrics", "structroc_1_1pipeline_1_1ReceiverSessionMetrics.html", "structroc_1_1pipeline_1_1ReceiverSessionMetrics" ],
        [ "ReceiverSlotMetrics", "structroc_1_1pipeline_1_1ReceiverSlotMetrics.html", "structroc_1_1pipeline_1_1ReceiverSlotMetrics" ],
        [ "PipelineLoop", "classroc_1_1pipeline_1_1PipelineLoop.html", "classroc_1_1pipeline_1_1PipelineLoop" ],
        [ "PipelineTask", "classroc_1_1pipeline_1_1PipelineTask.html", "classroc_1_1pipeline_1_1PipelineTask" ],
        [ "ReceiverEndpoint", "classroc_1_1pipeline_1_1ReceiverEndpoint.html", "classroc_1_1pipeline_1_1ReceiverEndpoint" ],
        [ "ReceiverLoop", "classroc_1_1pipeline_1_1ReceiverLoop.html", "classroc_1_1pipeline_1_1ReceiverLoop" ],
        [ "ReceiverSession", "classroc_1_1pipeline_1_1ReceiverSession.html", "classroc_1_1pipeline_1_1ReceiverSession" ],
        [ "ReceiverSessionGroup", "classroc_1_1pipeline_1_1ReceiverSessionGroup.html", "classroc_1_1pipeline_1_1ReceiverSessionGroup" ],
        [ "ReceiverSlot", "classroc_1_1pipeline_1_1ReceiverSlot.html", "classroc_1_1pipeline_1_1ReceiverSlot" ],
        [ "ReceiverSource", "classroc_1_1pipeline_1_1ReceiverSource.html", "classroc_1_1pipeline_1_1ReceiverSource" ],
        [ "ReceiverState", "classroc_1_1pipeline_1_1ReceiverState.html", "classroc_1_1pipeline_1_1ReceiverState" ],
        [ "SenderEndpoint", "classroc_1_1pipeline_1_1SenderEndpoint.html", "classroc_1_1pipeline_1_1SenderEndpoint" ],
        [ "SenderLoop", "classroc_1_1pipeline_1_1SenderLoop.html", "classroc_1_1pipeline_1_1SenderLoop" ],
        [ "SenderSession", "classroc_1_1pipeline_1_1SenderSession.html", "classroc_1_1pipeline_1_1SenderSession" ],
        [ "SenderSink", "classroc_1_1pipeline_1_1SenderSink.html", "classroc_1_1pipeline_1_1SenderSink" ],
        [ "SenderSlot", "classroc_1_1pipeline_1_1SenderSlot.html", "classroc_1_1pipeline_1_1SenderSlot" ],
        [ "TranscoderSink", "classroc_1_1pipeline_1_1TranscoderSink.html", "classroc_1_1pipeline_1_1TranscoderSink" ],
        [ "TranscoderSource", "classroc_1_1pipeline_1_1TranscoderSource.html", "classroc_1_1pipeline_1_1TranscoderSource" ]
      ] ],
      [ "rtcp", "namespaceroc_1_1rtcp.html", [
        [ "header", null, [
          [ "NtpTimestamp", "classroc_1_1rtcp_1_1header_1_1NtpTimestamp.html", "classroc_1_1rtcp_1_1header_1_1NtpTimestamp" ],
          [ "PacketHeader", "classroc_1_1rtcp_1_1header_1_1PacketHeader.html", "classroc_1_1rtcp_1_1header_1_1PacketHeader" ],
          [ "ReceptionReportBlock", "classroc_1_1rtcp_1_1header_1_1ReceptionReportBlock.html", "classroc_1_1rtcp_1_1header_1_1ReceptionReportBlock" ],
          [ "ReceiverReportPacket", "classroc_1_1rtcp_1_1header_1_1ReceiverReportPacket.html", "classroc_1_1rtcp_1_1header_1_1ReceiverReportPacket" ],
          [ "SenderReportPacket", "classroc_1_1rtcp_1_1header_1_1SenderReportPacket.html", "classroc_1_1rtcp_1_1header_1_1SenderReportPacket" ],
          [ "SdesChunkHeader", "classroc_1_1rtcp_1_1header_1_1SdesChunkHeader.html", "classroc_1_1rtcp_1_1header_1_1SdesChunkHeader" ],
          [ "SdesItemHeader", "classroc_1_1rtcp_1_1header_1_1SdesItemHeader.html", "classroc_1_1rtcp_1_1header_1_1SdesItemHeader" ],
          [ "SdesPacket", "classroc_1_1rtcp_1_1header_1_1SdesPacket.html", "classroc_1_1rtcp_1_1header_1_1SdesPacket" ],
          [ "ByeSourceHeader", "classroc_1_1rtcp_1_1header_1_1ByeSourceHeader.html", "classroc_1_1rtcp_1_1header_1_1ByeSourceHeader" ],
          [ "ByeReasonHeader", "classroc_1_1rtcp_1_1header_1_1ByeReasonHeader.html", "classroc_1_1rtcp_1_1header_1_1ByeReasonHeader" ],
          [ "ByePacket", "classroc_1_1rtcp_1_1header_1_1ByePacket.html", "classroc_1_1rtcp_1_1header_1_1ByePacket" ],
          [ "XrPacket", "classroc_1_1rtcp_1_1header_1_1XrPacket.html", "classroc_1_1rtcp_1_1header_1_1XrPacket" ],
          [ "XrBlockHeader", "classroc_1_1rtcp_1_1header_1_1XrBlockHeader.html", "classroc_1_1rtcp_1_1header_1_1XrBlockHeader" ],
          [ "XrRrtrBlock", "classroc_1_1rtcp_1_1header_1_1XrRrtrBlock.html", "classroc_1_1rtcp_1_1header_1_1XrRrtrBlock" ],
          [ "XrDlrrSubblock", "classroc_1_1rtcp_1_1header_1_1XrDlrrSubblock.html", "classroc_1_1rtcp_1_1header_1_1XrDlrrSubblock" ],
          [ "XrDlrrBlock", "classroc_1_1rtcp_1_1header_1_1XrDlrrBlock.html", "classroc_1_1rtcp_1_1header_1_1XrDlrrBlock" ]
        ] ],
        [ "Builder", "classroc_1_1rtcp_1_1Builder.html", "classroc_1_1rtcp_1_1Builder" ],
        [ "ByeTraverser", "classroc_1_1rtcp_1_1ByeTraverser.html", "classroc_1_1rtcp_1_1ByeTraverser" ],
        [ "Composer", "classroc_1_1rtcp_1_1Composer.html", "classroc_1_1rtcp_1_1Composer" ],
        [ "IReceiverHooks", "classroc_1_1rtcp_1_1IReceiverHooks.html", "classroc_1_1rtcp_1_1IReceiverHooks" ],
        [ "ISenderHooks", "classroc_1_1rtcp_1_1ISenderHooks.html", "classroc_1_1rtcp_1_1ISenderHooks" ],
        [ "SendingMetrics", "structroc_1_1rtcp_1_1SendingMetrics.html", "structroc_1_1rtcp_1_1SendingMetrics" ],
        [ "ReceptionMetrics", "structroc_1_1rtcp_1_1ReceptionMetrics.html", "structroc_1_1rtcp_1_1ReceptionMetrics" ],
        [ "LinkMetrics", "structroc_1_1rtcp_1_1LinkMetrics.html", "structroc_1_1rtcp_1_1LinkMetrics" ],
        [ "Parser", "classroc_1_1rtcp_1_1Parser.html", "classroc_1_1rtcp_1_1Parser" ],
        [ "SdesChunk", "structroc_1_1rtcp_1_1SdesChunk.html", "structroc_1_1rtcp_1_1SdesChunk" ],
        [ "SdesItem", "structroc_1_1rtcp_1_1SdesItem.html", "structroc_1_1rtcp_1_1SdesItem" ],
        [ "SdesTraverser", "classroc_1_1rtcp_1_1SdesTraverser.html", "classroc_1_1rtcp_1_1SdesTraverser" ],
        [ "Session", "classroc_1_1rtcp_1_1Session.html", "classroc_1_1rtcp_1_1Session" ],
        [ "Traverser", "classroc_1_1rtcp_1_1Traverser.html", "classroc_1_1rtcp_1_1Traverser" ],
        [ "XrTraverser", "classroc_1_1rtcp_1_1XrTraverser.html", "classroc_1_1rtcp_1_1XrTraverser" ]
      ] ],
      [ "rtp", "namespaceroc_1_1rtp.html", [
        [ "Composer", "classroc_1_1rtp_1_1Composer.html", "classroc_1_1rtp_1_1Composer" ],
        [ "Format", "structroc_1_1rtp_1_1Format.html", "structroc_1_1rtp_1_1Format" ],
        [ "FormatMap", "classroc_1_1rtp_1_1FormatMap.html", "classroc_1_1rtp_1_1FormatMap" ],
        [ "Header", "classroc_1_1rtp_1_1Header.html", "classroc_1_1rtp_1_1Header" ],
        [ "ExtentionHeader", "classroc_1_1rtp_1_1ExtentionHeader.html", "classroc_1_1rtp_1_1ExtentionHeader" ],
        [ "Parser", "classroc_1_1rtp_1_1Parser.html", "classroc_1_1rtp_1_1Parser" ],
        [ "Populator", "classroc_1_1rtp_1_1Populator.html", "classroc_1_1rtp_1_1Populator" ],
        [ "TimestampExtractor", "classroc_1_1rtp_1_1TimestampExtractor.html", "classroc_1_1rtp_1_1TimestampExtractor" ],
        [ "TimestampInjector", "classroc_1_1rtp_1_1TimestampInjector.html", "classroc_1_1rtp_1_1TimestampInjector" ],
        [ "ValidatorConfig", "structroc_1_1rtp_1_1ValidatorConfig.html", "structroc_1_1rtp_1_1ValidatorConfig" ],
        [ "Validator", "classroc_1_1rtp_1_1Validator.html", "classroc_1_1rtp_1_1Validator" ]
      ] ],
      [ "sdp", "namespaceroc_1_1sdp.html", [
        [ "ConnectionData", "classroc_1_1sdp_1_1ConnectionData.html", "classroc_1_1sdp_1_1ConnectionData" ],
        [ "MediaDescription", "classroc_1_1sdp_1_1MediaDescription.html", "classroc_1_1sdp_1_1MediaDescription" ],
        [ "SessionDescription", "classroc_1_1sdp_1_1SessionDescription.html", "classroc_1_1sdp_1_1SessionDescription" ]
      ] ],
      [ "sndio", "namespaceroc_1_1sndio.html", [
        [ "BackendDispatcher", "classroc_1_1sndio_1_1BackendDispatcher.html", "classroc_1_1sndio_1_1BackendDispatcher" ],
        [ "BackendMap", "classroc_1_1sndio_1_1BackendMap.html", "classroc_1_1sndio_1_1BackendMap" ],
        [ "Config", "structroc_1_1sndio_1_1Config.html", "structroc_1_1sndio_1_1Config" ],
        [ "DriverInfo", "structroc_1_1sndio_1_1DriverInfo.html", "structroc_1_1sndio_1_1DriverInfo" ],
        [ "IBackend", "classroc_1_1sndio_1_1IBackend.html", "classroc_1_1sndio_1_1IBackend" ],
        [ "IDevice", "classroc_1_1sndio_1_1IDevice.html", "classroc_1_1sndio_1_1IDevice" ],
        [ "ISink", "classroc_1_1sndio_1_1ISink.html", "classroc_1_1sndio_1_1ISink" ],
        [ "ISource", "classroc_1_1sndio_1_1ISource.html", "classroc_1_1sndio_1_1ISource" ],
        [ "Pump", "classroc_1_1sndio_1_1Pump.html", "classroc_1_1sndio_1_1Pump" ],
        [ "PulseaudioBackend", "classroc_1_1sndio_1_1PulseaudioBackend.html", "classroc_1_1sndio_1_1PulseaudioBackend" ],
        [ "PulseaudioDevice", "classroc_1_1sndio_1_1PulseaudioDevice.html", "classroc_1_1sndio_1_1PulseaudioDevice" ],
        [ "PulseaudioSink", "classroc_1_1sndio_1_1PulseaudioSink.html", "classroc_1_1sndio_1_1PulseaudioSink" ],
        [ "PulseaudioSource", "classroc_1_1sndio_1_1PulseaudioSource.html", "classroc_1_1sndio_1_1PulseaudioSource" ],
        [ "SoxBackend", "classroc_1_1sndio_1_1SoxBackend.html", "classroc_1_1sndio_1_1SoxBackend" ],
        [ "SoxSink", "classroc_1_1sndio_1_1SoxSink.html", "classroc_1_1sndio_1_1SoxSink" ],
        [ "SoxSource", "classroc_1_1sndio_1_1SoxSource.html", "classroc_1_1sndio_1_1SoxSource" ]
      ] ]
    ] ]
];