var hierarchy =
[
    [ "roc::core::AlignedStorage< Size >", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignedStorage< 0 *sizeof(T)>", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignedStorage< 0 *SlotSize >", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignedStorage< NumEmbeddedBuckets *sizeof(roc::core::HashmapImpl::Bucket)>", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignedStorage< sizeof(T) >", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignedStorage< sizeof(T)>", "classroc_1_1core_1_1AlignedStorage.html", null ],
    [ "roc::core::AlignMax", "unionroc_1_1core_1_1AlignMax.html", null ],
    [ "roc::core::AlignOps", "classroc_1_1core_1_1AlignOps.html", null ],
    [ "AllocationPolicy", null, [
      [ "roc::core::RefCounted< T, AllocationPolicy >", "classroc_1_1core_1_1RefCounted.html", null ]
    ] ],
    [ "roc::core::ArenaAllocation", "classroc_1_1core_1_1ArenaAllocation.html", [
      [ "roc::core::RefCounted< ReceiverSlot, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::pipeline::ReceiverSlot", "classroc_1_1pipeline_1_1ReceiverSlot.html", null ]
      ] ],
      [ "roc::core::RefCounted< MediaDescription, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::sdp::MediaDescription", "classroc_1_1sdp_1_1MediaDescription.html", null ]
      ] ],
      [ "roc::core::RefCounted< BasicPort, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::netio::BasicPort", "classroc_1_1netio_1_1BasicPort.html", [
          [ "roc::netio::TcpConnectionPort", "classroc_1_1netio_1_1TcpConnectionPort.html", null ],
          [ "roc::netio::TcpServerPort", "classroc_1_1netio_1_1TcpServerPort.html", null ],
          [ "roc::netio::UdpPort", "classroc_1_1netio_1_1UdpPort.html", null ]
        ] ]
      ] ],
      [ "roc::core::RefCounted< IResampler, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::audio::IResampler", "classroc_1_1audio_1_1IResampler.html", [
          [ "roc::audio::BuiltinResampler", "classroc_1_1audio_1_1BuiltinResampler.html", null ],
          [ "roc::audio::DecimationResampler", "classroc_1_1audio_1_1DecimationResampler.html", null ],
          [ "roc::audio::SpeexResampler", "classroc_1_1audio_1_1SpeexResampler.html", null ]
        ] ]
      ] ],
      [ "roc::core::RefCounted< ReceiverSession, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::pipeline::ReceiverSession", "classroc_1_1pipeline_1_1ReceiverSession.html", null ]
      ] ],
      [ "roc::core::RefCounted< BasicControlEndpoint, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::ctl::BasicControlEndpoint", "classroc_1_1ctl_1_1BasicControlEndpoint.html", null ]
      ] ],
      [ "roc::core::RefCounted< ReceiverEndpoint, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::pipeline::ReceiverEndpoint", "classroc_1_1pipeline_1_1ReceiverEndpoint.html", null ]
      ] ],
      [ "roc::core::RefCounted< SenderSlot, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::pipeline::SenderSlot", "classroc_1_1pipeline_1_1SenderSlot.html", null ]
      ] ]
    ] ],
    [ "roc::core::AtomicOps", "classroc_1_1core_1_1AtomicOps.html", null ],
    [ "roc::core::HashmapImpl::Bucket", "structroc_1_1core_1_1HashmapImpl_1_1Bucket.html", null ],
    [ "roc::rtcp::header::ByePacket", "classroc_1_1rtcp_1_1header_1_1ByePacket.html", null ],
    [ "roc::rtcp::header::ByeReasonHeader", "classroc_1_1rtcp_1_1header_1_1ByeReasonHeader.html", null ],
    [ "roc::rtcp::header::ByeSourceHeader", "classroc_1_1rtcp_1_1header_1_1ByeSourceHeader.html", null ],
    [ "roc::rtcp::ByeTraverser", "classroc_1_1rtcp_1_1ByeTraverser.html", null ],
    [ "roc::audio::ChannelMapRule", "structroc_1_1audio_1_1ChannelMapRule.html", null ],
    [ "roc::audio::ChannelMapTable", "structroc_1_1audio_1_1ChannelMapTable.html", null ],
    [ "roc::audio::ChannelMaskName", "structroc_1_1audio_1_1ChannelMaskName.html", null ],
    [ "roc::audio::ChannelOrderTable", "structroc_1_1audio_1_1ChannelOrderTable.html", null ],
    [ "roc::audio::ChannelPositionName", "structroc_1_1audio_1_1ChannelPositionName.html", null ],
    [ "roc::audio::ChannelSet", "classroc_1_1audio_1_1ChannelSet.html", null ],
    [ "roc::fec::CodecConfig", "structroc_1_1fec_1_1CodecConfig.html", null ],
    [ "roc::rtcp::Config", "structroc_1_1rtcp_1_1Config.html", null ],
    [ "roc::sndio::Config", "structroc_1_1sndio_1_1Config.html", null ],
    [ "roc::sdp::ConnectionData", "classroc_1_1sdp_1_1ConnectionData.html", null ],
    [ "roc::node::ContextConfig", "structroc_1_1node_1_1ContextConfig.html", null ],
    [ "roc::core::CsvConfig", "structroc_1_1core_1_1CsvConfig.html", null ],
    [ "roc::core::CsvEntry", "structroc_1_1core_1_1CsvEntry.html", null ],
    [ "roc::core::CustomAllocation", "classroc_1_1core_1_1CustomAllocation.html", null ],
    [ "roc::sndio::DriverInfo", "structroc_1_1sndio_1_1DriverInfo.html", null ],
    [ "roc::rtp::Encoding", "structroc_1_1rtp_1_1Encoding.html", null ],
    [ "roc::core::EndianOps", "classroc_1_1core_1_1EndianOps.html", null ],
    [ "roc::rtp::ExtentionHeader", "classroc_1_1rtp_1_1ExtentionHeader.html", null ],
    [ "roc::packet::FEC", "structroc_1_1packet_1_1FEC.html", null ],
    [ "roc::audio::FeedbackConfig", "structroc_1_1audio_1_1FeedbackConfig.html", null ],
    [ "FileMap", "structFileMap.html", null ],
    [ "roc::rtp::FilterConfig", "structroc_1_1rtp_1_1FilterConfig.html", null ],
    [ "roc::audio::FreqEstimatorConfig", "structroc_1_1audio_1_1FreqEstimatorConfig.html", null ],
    [ "roc::core::GlobalDestructor", "classroc_1_1core_1_1GlobalDestructor.html", null ],
    [ "roc::core::HashmapData", "structroc_1_1core_1_1HashmapData.html", null ],
    [ "roc::core::HashmapImpl", "classroc_1_1core_1_1HashmapImpl.html", null ],
    [ "roc::rtp::Header", "classroc_1_1rtp_1_1Header.html", null ],
    [ "roc::core::IArena", "classroc_1_1core_1_1IArena.html", [
      [ "roc::core::HeapArena", "classroc_1_1core_1_1HeapArena.html", null ],
      [ "roc::core::LimitedArena", "classroc_1_1core_1_1LimitedArena.html", null ],
      [ "roc::core::NoopArenaImpl", "classroc_1_1core_1_1NoopArenaImpl.html", null ]
    ] ],
    [ "roc::sndio::IBackend", "classroc_1_1sndio_1_1IBackend.html", [
      [ "roc::sndio::PulseaudioBackend", "classroc_1_1sndio_1_1PulseaudioBackend.html", null ],
      [ "roc::sndio::SndfileBackend", "classroc_1_1sndio_1_1SndfileBackend.html", null ],
      [ "roc::sndio::SoxBackend", "classroc_1_1sndio_1_1SoxBackend.html", null ],
      [ "roc::sndio::WavBackend", "classroc_1_1sndio_1_1WavBackend.html", null ]
    ] ],
    [ "roc::fec::IBlockDecoder", "classroc_1_1fec_1_1IBlockDecoder.html", [
      [ "roc::fec::OpenfecDecoder", "classroc_1_1fec_1_1OpenfecDecoder.html", null ]
    ] ],
    [ "roc::fec::IBlockEncoder", "classroc_1_1fec_1_1IBlockEncoder.html", [
      [ "roc::fec::OpenfecEncoder", "classroc_1_1fec_1_1OpenfecEncoder.html", null ]
    ] ],
    [ "roc::netio::ICloseHandler", "classroc_1_1netio_1_1ICloseHandler.html", [
      [ "roc::netio::NetworkLoop", "classroc_1_1netio_1_1NetworkLoop.html", null ],
      [ "roc::netio::TcpServerPort", "classroc_1_1netio_1_1TcpServerPort.html", null ]
    ] ],
    [ "roc::packet::IComposer", "classroc_1_1packet_1_1IComposer.html", [
      [ "roc::fec::Composer< PayloadID, Type, Pos >", "classroc_1_1fec_1_1Composer.html", null ],
      [ "roc::rtcp::Composer", "classroc_1_1rtcp_1_1Composer.html", null ],
      [ "roc::rtp::Composer", "classroc_1_1rtp_1_1Composer.html", null ]
    ] ],
    [ "roc::netio::IConn", "classroc_1_1netio_1_1IConn.html", [
      [ "roc::netio::TcpConnectionPort", "classroc_1_1netio_1_1TcpConnectionPort.html", null ]
    ] ],
    [ "roc::netio::IConnAcceptor", "classroc_1_1netio_1_1IConnAcceptor.html", null ],
    [ "roc::ctl::IControlTaskCompleter", "classroc_1_1ctl_1_1IControlTaskCompleter.html", null ],
    [ "roc::ctl::IControlTaskExecutor", "classroc_1_1ctl_1_1IControlTaskExecutor.html", [
      [ "roc::ctl::ControlTaskExecutor< ControlLoop >", "classroc_1_1ctl_1_1ControlTaskExecutor.html", [
        [ "roc::ctl::ControlLoop", "classroc_1_1ctl_1_1ControlLoop.html", null ]
      ] ],
      [ "roc::ctl::ControlTaskExecutor< E >", "classroc_1_1ctl_1_1ControlTaskExecutor.html", null ]
    ] ],
    [ "roc::sndio::IDevice", "classroc_1_1sndio_1_1IDevice.html", [
      [ "roc::sndio::ISink", "classroc_1_1sndio_1_1ISink.html", [
        [ "roc::pipeline::SenderLoop", "classroc_1_1pipeline_1_1SenderLoop.html", null ],
        [ "roc::pipeline::SenderSink", "classroc_1_1pipeline_1_1SenderSink.html", null ],
        [ "roc::pipeline::TranscoderSink", "classroc_1_1pipeline_1_1TranscoderSink.html", null ],
        [ "roc::sndio::PulseaudioDevice", "classroc_1_1sndio_1_1PulseaudioDevice.html", null ],
        [ "roc::sndio::SndfileSink", "classroc_1_1sndio_1_1SndfileSink.html", null ],
        [ "roc::sndio::SoxSink", "classroc_1_1sndio_1_1SoxSink.html", null ],
        [ "roc::sndio::WavSink", "classroc_1_1sndio_1_1WavSink.html", null ]
      ] ],
      [ "roc::sndio::ISource", "classroc_1_1sndio_1_1ISource.html", [
        [ "roc::pipeline::ReceiverLoop", "classroc_1_1pipeline_1_1ReceiverLoop.html", null ],
        [ "roc::pipeline::ReceiverSource", "classroc_1_1pipeline_1_1ReceiverSource.html", null ],
        [ "roc::pipeline::TranscoderSource", "classroc_1_1pipeline_1_1TranscoderSource.html", null ],
        [ "roc::sndio::PulseaudioDevice", "classroc_1_1sndio_1_1PulseaudioDevice.html", null ],
        [ "roc::sndio::SndfileSource", "classroc_1_1sndio_1_1SndfileSource.html", null ],
        [ "roc::sndio::SoxSource", "classroc_1_1sndio_1_1SoxSource.html", null ],
        [ "roc::sndio::WavSource", "classroc_1_1sndio_1_1WavSource.html", null ]
      ] ]
    ] ],
    [ "roc::audio::IFrameDecoder", "classroc_1_1audio_1_1IFrameDecoder.html", [
      [ "roc::audio::PcmDecoder", "classroc_1_1audio_1_1PcmDecoder.html", null ]
    ] ],
    [ "roc::audio::IFrameEncoder", "classroc_1_1audio_1_1IFrameEncoder.html", [
      [ "roc::audio::PcmEncoder", "classroc_1_1audio_1_1PcmEncoder.html", null ]
    ] ],
    [ "roc::packet::ILinkMeter", "classroc_1_1packet_1_1ILinkMeter.html", [
      [ "roc::rtp::LinkMeter", "classroc_1_1rtp_1_1LinkMeter.html", null ]
    ] ],
    [ "roc::netio::INetworkTaskCompleter", "classroc_1_1netio_1_1INetworkTaskCompleter.html", null ],
    [ "roc::packet::IParser", "classroc_1_1packet_1_1IParser.html", [
      [ "roc::fec::Parser< PayloadID, Type, Pos >", "classroc_1_1fec_1_1Parser.html", null ],
      [ "roc::rtcp::Parser", "classroc_1_1rtcp_1_1Parser.html", null ],
      [ "roc::rtp::Parser", "classroc_1_1rtp_1_1Parser.html", null ]
    ] ],
    [ "roc::rtcp::IParticipant", "classroc_1_1rtcp_1_1IParticipant.html", [
      [ "roc::pipeline::ReceiverSessionGroup", "classroc_1_1pipeline_1_1ReceiverSessionGroup.html", null ],
      [ "roc::pipeline::SenderSession", "classroc_1_1pipeline_1_1SenderSession.html", null ]
    ] ],
    [ "roc::pipeline::IPipelineTaskCompleter", "classroc_1_1pipeline_1_1IPipelineTaskCompleter.html", null ],
    [ "roc::pipeline::IPipelineTaskScheduler", "classroc_1_1pipeline_1_1IPipelineTaskScheduler.html", [
      [ "roc::node::Receiver", "classroc_1_1node_1_1Receiver.html", null ],
      [ "roc::node::ReceiverDecoder", "classroc_1_1node_1_1ReceiverDecoder.html", null ],
      [ "roc::node::Sender", "classroc_1_1node_1_1Sender.html", null ],
      [ "roc::node::SenderEncoder", "classroc_1_1node_1_1SenderEncoder.html", null ]
    ] ],
    [ "roc::core::IPool", "classroc_1_1core_1_1IPool.html", [
      [ "roc::core::SlabPool< Stream, PreallocatedStreams >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< SourceNode, PreallocatedSources >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< roc::core::Buffer >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Route, PreallocatedRoutes >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< roc::packet::Packet >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Address, PreallocatedAddresses >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Slot >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Node, PreallocatedNodes >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::LimitedPool", "classroc_1_1core_1_1LimitedPool.html", null ],
      [ "roc::core::SlabPool< T, EmbeddedCapacity >", "classroc_1_1core_1_1SlabPool.html", null ]
    ] ],
    [ "roc::packet::IReader", "classroc_1_1packet_1_1IReader.html", [
      [ "roc::fec::Reader", "classroc_1_1fec_1_1Reader.html", null ],
      [ "roc::packet::ConcurrentQueue", "classroc_1_1packet_1_1ConcurrentQueue.html", null ],
      [ "roc::packet::DelayedReader", "classroc_1_1packet_1_1DelayedReader.html", null ],
      [ "roc::packet::Queue", "classroc_1_1packet_1_1Queue.html", null ],
      [ "roc::packet::SortedQueue", "classroc_1_1packet_1_1SortedQueue.html", null ],
      [ "roc::rtp::Filter", "classroc_1_1rtp_1_1Filter.html", null ],
      [ "roc::rtp::LinkMeter", "classroc_1_1rtp_1_1LinkMeter.html", null ],
      [ "roc::rtp::TimestampInjector", "classroc_1_1rtp_1_1TimestampInjector.html", null ]
    ] ],
    [ "roc::netio::IResolverRequestHandler", "classroc_1_1netio_1_1IResolverRequestHandler.html", [
      [ "roc::netio::NetworkLoop", "classroc_1_1netio_1_1NetworkLoop.html", null ]
    ] ],
    [ "roc::packet::ISequencer", "classroc_1_1packet_1_1ISequencer.html", [
      [ "roc::rtp::Sequencer", "classroc_1_1rtp_1_1Sequencer.html", null ]
    ] ],
    [ "roc::rtcp::ByeTraverser::Iterator", "classroc_1_1rtcp_1_1ByeTraverser_1_1Iterator.html", null ],
    [ "roc::rtcp::SdesTraverser::Iterator", "classroc_1_1rtcp_1_1SdesTraverser_1_1Iterator.html", null ],
    [ "roc::rtcp::Traverser::Iterator", "classroc_1_1rtcp_1_1Traverser_1_1Iterator.html", null ],
    [ "roc::rtcp::XrTraverser::Iterator", "classroc_1_1rtcp_1_1XrTraverser_1_1Iterator.html", null ],
    [ "roc::netio::ITerminateHandler", "classroc_1_1netio_1_1ITerminateHandler.html", [
      [ "roc::netio::NetworkLoop", "classroc_1_1netio_1_1NetworkLoop.html", null ],
      [ "roc::netio::TcpServerPort", "classroc_1_1netio_1_1TcpServerPort.html", null ]
    ] ],
    [ "roc::packet::IWriter", "classroc_1_1packet_1_1IWriter.html", [
      [ "roc::fec::Writer", "classroc_1_1fec_1_1Writer.html", null ],
      [ "roc::netio::UdpPort", "classroc_1_1netio_1_1UdpPort.html", null ],
      [ "roc::packet::ConcurrentQueue", "classroc_1_1packet_1_1ConcurrentQueue.html", null ],
      [ "roc::packet::Interleaver", "classroc_1_1packet_1_1Interleaver.html", null ],
      [ "roc::packet::Queue", "classroc_1_1packet_1_1Queue.html", null ],
      [ "roc::packet::Router", "classroc_1_1packet_1_1Router.html", null ],
      [ "roc::packet::Shipper", "classroc_1_1packet_1_1Shipper.html", null ],
      [ "roc::packet::SortedQueue", "classroc_1_1packet_1_1SortedQueue.html", null ],
      [ "roc::pipeline::ReceiverEndpoint", "classroc_1_1pipeline_1_1ReceiverEndpoint.html", null ],
      [ "roc::pipeline::SenderEndpoint", "classroc_1_1pipeline_1_1SenderEndpoint.html", null ],
      [ "roc::rtp::LinkMeter", "classroc_1_1rtp_1_1LinkMeter.html", null ],
      [ "roc::rtp::TimestampExtractor", "classroc_1_1rtp_1_1TimestampExtractor.html", null ]
    ] ],
    [ "roc::audio::LatencyConfig", "structroc_1_1audio_1_1LatencyConfig.html", null ],
    [ "roc::audio::LatencyMetrics", "structroc_1_1audio_1_1LatencyMetrics.html", null ],
    [ "roc::fec::LDPC_Repair_PayloadID", "classroc_1_1fec_1_1LDPC__Repair__PayloadID.html", null ],
    [ "roc::fec::LDPC_Source_PayloadID", "classroc_1_1fec_1_1LDPC__Source__PayloadID.html", null ],
    [ "roc::packet::LinkMetrics", "structroc_1_1packet_1_1LinkMetrics.html", null ],
    [ "roc::core::ListData", "structroc_1_1core_1_1ListData.html", null ],
    [ "roc::core::LogMessage", "structroc_1_1core_1_1LogMessage.html", null ],
    [ "roc::rtcp::LossEstimator", "classroc_1_1rtcp_1_1LossEstimator.html", null ],
    [ "roc::core::ManualAllocation", "classroc_1_1core_1_1ManualAllocation.html", [
      [ "roc::core::RefCounted< Context, core::ManualAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::node::Context", "classroc_1_1node_1_1Context.html", null ]
      ] ],
      [ "roc::core::RefCounted< IConnHandler, core::ManualAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::netio::IConnHandler", "classroc_1_1netio_1_1IConnHandler.html", null ]
      ] ]
    ] ],
    [ "roc::core::MemoryOps", "classroc_1_1core_1_1MemoryOps.html", null ],
    [ "roc::core::MovStats< T >", "classroc_1_1core_1_1MovStats.html", null ],
    [ "roc::core::MpscQueueData", "structroc_1_1core_1_1MpscQueueData.html", null ],
    [ "roc::core::MpscQueueImpl", "classroc_1_1core_1_1MpscQueueImpl.html", null ],
    [ "roc::core::NonCopyable< Tag >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::Array< roc::sndio::IBackend *, MaxBackends >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< Route, 2 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::core::Slice< uint8_t > >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::rtcp::RecvReport, PreallocatedStreams >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::pipeline::ReceiverParticipantMetrics, 8 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< float >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::sndio::DriverInfo, MaxDrivers >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< SharedPtr< Packet > >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< size_t >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< unsigned, 2 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< Address *, PreallocatedAddresses >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< char, 32 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< void * >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< char >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< sox_sample_t >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< bool >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< sample_t >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::pipeline::SenderParticipantMetrics, 8 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< roc::sdp::ConnectionData, 1 >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Array< Stream *, PreallocatedStreams >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Atomic< uint32_t >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< int >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< int32_t >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< size_t >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< roc::packet::IWriter * >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< roc::packet::IReader * >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< roc::core::Semaphore * >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Hashmap< Stream, PreallocatedStreams >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< CnameNode, PreallocatedRoutes, roc::core::NoOwnership >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< SessionNode, PreallocatedRoutes, roc::core::NoOwnership >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< AddressNode, PreallocatedRoutes, roc::core::NoOwnership >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< Address, PreallocatedAddresses >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< Slot >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< Node, PreallocatedNodes >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::Hashmap< SourceNode, PreallocatedRoutes, roc::core::NoOwnership >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::List< SourceNode >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::ctl::BasicControlEndpoint >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::audio::IFrameWriter, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::ctl::ControlTask, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< Slot, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< Slab, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::audio::IFrameReader, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::sdp::MediaDescription >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::pipeline::ReceiverSlot >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< Route >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::pipeline::SenderSlot >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::netio::TcpConnectionPort >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::packet::Packet >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::netio::BasicPort >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< Stream, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< roc::pipeline::ReceiverSession >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::List< Address, roc::core::NoOwnership >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::MpscQueue< roc::pipeline::PipelineTask, roc::core::NoOwnership >", "classroc_1_1core_1_1MpscQueue.html", null ],
      [ "roc::core::MpscQueue< roc::ctl::ControlTask, roc::core::NoOwnership >", "classroc_1_1core_1_1MpscQueue.html", null ],
      [ "roc::core::MpscQueue< roc::packet::Packet >", "classroc_1_1core_1_1MpscQueue.html", null ],
      [ "roc::core::MpscQueue< roc::netio::NetworkTask, roc::core::NoOwnership >", "classroc_1_1core_1_1MpscQueue.html", null ],
      [ "roc::core::Optional< roc::audio::Watchdog >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ResamplerWriter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::sndio::WavHeader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::TimestampExtractor >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::fec::Writer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::Composer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::LatencyMonitor >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::TimestampInjector >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::Router >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtcp::Communicator >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::SortedQueue >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::FreqEstimator >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::pipeline::ReceiverEndpoint >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< IBufferWriter, ROC_MAX(sizeof(StaticBufferWriter), sizeof(DynamicBufferWriter))>", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::core::SlabPool< roc::core::Buffer > >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::pipeline::SenderEndpoint >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ChannelMapperReader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::DelayedReader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< ArenaAllocation >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::PcmMapperWriter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::Shipper >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::core::SlabPool< roc::packet::Packet > >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::PcmMapperReader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ResamplerReader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::Filter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::Interleaver >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::core::Ticker >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::Mixer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::fec::Reader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtcp::Parser >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::core::Semaphore >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::Identity >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::Depacketizer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::LinkMeter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::Parser >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::sndio::WavBackend >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::FeedbackMonitor >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtp::Sequencer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ProfilingReader >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::rtcp::Composer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::core::RateLimiter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ProfilingWriter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::ChannelMapperWriter >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::audio::Packetizer >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Optional< roc::packet::ConcurrentQueue >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::RefCounted< ReceiverSlot, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Context, core::ManualAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< MediaDescription, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Address, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< BasicPort, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< IResampler, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Route, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< ReceiverSession, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< BasicControlEndpoint, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Node, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< ReceiverEndpoint, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Slot, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Buffer, PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::core::Buffer", "classroc_1_1core_1_1Buffer.html", null ]
      ] ],
      [ "roc::core::RefCounted< SenderSlot, core::ArenaAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Stream, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< SourceNode, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< IConnHandler, core::ManualAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Packet, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", [
        [ "roc::packet::Packet", "classroc_1_1packet_1_1Packet.html", null ]
      ] ],
      [ "roc::core::ScopedPtr< roc::fec::IBlockEncoder >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::ScopedPtr< roc::packet::IParser >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::ScopedPtr< roc::audio::IFrameDecoder >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::ScopedPtr< roc::fec::IBlockDecoder >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::ScopedPtr< roc::packet::IComposer >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::ScopedPtr< roc::audio::IFrameEncoder >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::Seqlock< nanoseconds_t >", "classroc_1_1core_1_1Seqlock.html", null ],
      [ "roc::core::Seqlock< uint64_t >", "classroc_1_1core_1_1Seqlock.html", null ],
      [ "roc::core::Seqlock< core::nanoseconds_t >", "classroc_1_1core_1_1Seqlock.html", null ],
      [ "roc::core::SlabPool< Stream, PreallocatedStreams >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< SourceNode, PreallocatedSources >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< roc::core::Buffer >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Route, PreallocatedRoutes >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< roc::packet::Packet >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Address, PreallocatedAddresses >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Slot >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPool< Node, PreallocatedNodes >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SpscRingBuffer< roc::core::CsvEntry >", "classroc_1_1core_1_1SpscRingBuffer.html", null ],
      [ "roc::address::EndpointUri", "classroc_1_1address_1_1EndpointUri.html", null ],
      [ "roc::address::IoUri", "classroc_1_1address_1_1IoUri.html", null ],
      [ "roc::address::ProtocolMap", "classroc_1_1address_1_1ProtocolMap.html", null ],
      [ "roc::address::endpoint_uri_to_str", "classroc_1_1address_1_1endpoint__uri__to__str.html", null ],
      [ "roc::address::io_uri_to_str", "classroc_1_1address_1_1io__uri__to__str.html", null ],
      [ "roc::address::socket_addr_to_str", "classroc_1_1address_1_1socket__addr__to__str.html", null ],
      [ "roc::audio::BuiltinResampler", "classroc_1_1audio_1_1BuiltinResampler.html", null ],
      [ "roc::audio::ChannelMapper", "classroc_1_1audio_1_1ChannelMapper.html", null ],
      [ "roc::audio::ChannelMapperMatrix", "classroc_1_1audio_1_1ChannelMapperMatrix.html", null ],
      [ "roc::audio::ChannelMapperReader", "classroc_1_1audio_1_1ChannelMapperReader.html", null ],
      [ "roc::audio::ChannelMapperWriter", "classroc_1_1audio_1_1ChannelMapperWriter.html", null ],
      [ "roc::audio::DecimationResampler", "classroc_1_1audio_1_1DecimationResampler.html", null ],
      [ "roc::audio::Depacketizer", "classroc_1_1audio_1_1Depacketizer.html", null ],
      [ "roc::audio::Fanout", "classroc_1_1audio_1_1Fanout.html", null ],
      [ "roc::audio::FeedbackMonitor", "classroc_1_1audio_1_1FeedbackMonitor.html", null ],
      [ "roc::audio::Frame", "classroc_1_1audio_1_1Frame.html", null ],
      [ "roc::audio::FrameFactory", "classroc_1_1audio_1_1FrameFactory.html", null ],
      [ "roc::audio::FreqEstimator", "classroc_1_1audio_1_1FreqEstimator.html", null ],
      [ "roc::audio::LatencyMonitor", "classroc_1_1audio_1_1LatencyMonitor.html", null ],
      [ "roc::audio::LatencyTuner", "classroc_1_1audio_1_1LatencyTuner.html", null ],
      [ "roc::audio::Mixer", "classroc_1_1audio_1_1Mixer.html", null ],
      [ "roc::audio::NullWriter", "classroc_1_1audio_1_1NullWriter.html", null ],
      [ "roc::audio::Packetizer", "classroc_1_1audio_1_1Packetizer.html", null ],
      [ "roc::audio::PcmDecoder", "classroc_1_1audio_1_1PcmDecoder.html", null ],
      [ "roc::audio::PcmEncoder", "classroc_1_1audio_1_1PcmEncoder.html", null ],
      [ "roc::audio::PcmMapper", "classroc_1_1audio_1_1PcmMapper.html", null ],
      [ "roc::audio::PcmMapperReader", "classroc_1_1audio_1_1PcmMapperReader.html", null ],
      [ "roc::audio::PcmMapperWriter", "classroc_1_1audio_1_1PcmMapperWriter.html", null ],
      [ "roc::audio::Profiler", "classroc_1_1audio_1_1Profiler.html", null ],
      [ "roc::audio::ProfilingReader", "classroc_1_1audio_1_1ProfilingReader.html", null ],
      [ "roc::audio::ProfilingWriter", "classroc_1_1audio_1_1ProfilingWriter.html", null ],
      [ "roc::audio::ResamplerMap", "classroc_1_1audio_1_1ResamplerMap.html", null ],
      [ "roc::audio::ResamplerReader", "classroc_1_1audio_1_1ResamplerReader.html", null ],
      [ "roc::audio::ResamplerWriter", "classroc_1_1audio_1_1ResamplerWriter.html", null ],
      [ "roc::audio::SpeexResampler", "classroc_1_1audio_1_1SpeexResampler.html", null ],
      [ "roc::audio::Watchdog", "classroc_1_1audio_1_1Watchdog.html", null ],
      [ "roc::audio::channel_set_to_str", "classroc_1_1audio_1_1channel__set__to__str.html", null ],
      [ "roc::audio::sample_spec_to_str", "classroc_1_1audio_1_1sample__spec__to__str.html", null ],
      [ "roc::core::Array< T, EmbeddedCapacity >", "classroc_1_1core_1_1Array.html", null ],
      [ "roc::core::Atomic< T >", "classroc_1_1core_1_1Atomic.html", null ],
      [ "roc::core::Atomic< T * >", "classroc_1_1core_1_1Atomic_3_01T_01_5_01_4.html", null ],
      [ "roc::core::Cond", "classroc_1_1core_1_1Cond.html", null ],
      [ "roc::core::CrashHandler", "classroc_1_1core_1_1CrashHandler.html", null ],
      [ "roc::core::Hashmap< T, EmbeddedCapacity, OwnershipPolicy, Node >", "classroc_1_1core_1_1Hashmap.html", null ],
      [ "roc::core::HeapArena", "classroc_1_1core_1_1HeapArena.html", null ],
      [ "roc::core::LimitedArena", "classroc_1_1core_1_1LimitedArena.html", null ],
      [ "roc::core::List< T, OwnershipPolicy, Node >", "classroc_1_1core_1_1List.html", null ],
      [ "roc::core::ListImpl", "classroc_1_1core_1_1ListImpl.html", null ],
      [ "roc::core::LogBackend", "classroc_1_1core_1_1LogBackend.html", null ],
      [ "roc::core::LogBackend", "classroc_1_1core_1_1LogBackend.html", null ],
      [ "roc::core::Logger", "classroc_1_1core_1_1Logger.html", null ],
      [ "roc::core::MemoryLimiter", "classroc_1_1core_1_1MemoryLimiter.html", null ],
      [ "roc::core::MpscQueue< T, OwnershipPolicy, Node >", "classroc_1_1core_1_1MpscQueue.html", null ],
      [ "roc::core::Mutex", "classroc_1_1core_1_1Mutex.html", null ],
      [ "roc::core::NoopArenaImpl", "classroc_1_1core_1_1NoopArenaImpl.html", null ],
      [ "roc::core::Optional< T, Size >", "classroc_1_1core_1_1Optional.html", null ],
      [ "roc::core::Printer", "classroc_1_1core_1_1Printer.html", null ],
      [ "roc::core::RateLimiter", "classroc_1_1core_1_1RateLimiter.html", null ],
      [ "roc::core::RingQueue< T, EmbeddedCapacity >", "classroc_1_1core_1_1RingQueue.html", null ],
      [ "roc::core::ScopedLock< Mutex >", "classroc_1_1core_1_1ScopedLock.html", null ],
      [ "roc::core::ScopedPtr< T, AllocationPolicy >", "classroc_1_1core_1_1ScopedPtr.html", null ],
      [ "roc::core::Semaphore", "classroc_1_1core_1_1Semaphore.html", null ],
      [ "roc::core::Semaphore", "classroc_1_1core_1_1Semaphore.html", null ],
      [ "roc::core::Seqlock< T >", "classroc_1_1core_1_1Seqlock.html", null ],
      [ "roc::core::Singleton< T >", "classroc_1_1core_1_1Singleton.html", null ],
      [ "roc::core::SlabPool< T, EmbeddedCapacity >", "classroc_1_1core_1_1SlabPool.html", null ],
      [ "roc::core::SlabPoolImpl", "classroc_1_1core_1_1SlabPoolImpl.html", null ],
      [ "roc::core::SpscByteBuffer", "classroc_1_1core_1_1SpscByteBuffer.html", null ],
      [ "roc::core::SpscRingBuffer< T >", "classroc_1_1core_1_1SpscRingBuffer.html", null ],
      [ "roc::core::StringBuffer", "classroc_1_1core_1_1StringBuffer.html", null ],
      [ "roc::core::StringBuilder", "classroc_1_1core_1_1StringBuilder.html", null ],
      [ "roc::core::StringList", "classroc_1_1core_1_1StringList.html", null ],
      [ "roc::core::TempFile", "classroc_1_1core_1_1TempFile.html", null ],
      [ "roc::core::Ticker", "classroc_1_1core_1_1Ticker.html", null ],
      [ "roc::core::Timer", "classroc_1_1core_1_1Timer.html", null ],
      [ "roc::core::errno_to_str", "classroc_1_1core_1_1errno__to__str.html", null ],
      [ "roc::ctl::ControlInterfaceMap", "classroc_1_1ctl_1_1ControlInterfaceMap.html", null ],
      [ "roc::ctl::ControlLoop", "classroc_1_1ctl_1_1ControlLoop.html", null ],
      [ "roc::fec::CodecMap", "classroc_1_1fec_1_1CodecMap.html", null ],
      [ "roc::fec::Composer< PayloadID, Type, Pos >", "classroc_1_1fec_1_1Composer.html", null ],
      [ "roc::fec::OpenfecDecoder", "classroc_1_1fec_1_1OpenfecDecoder.html", null ],
      [ "roc::fec::OpenfecEncoder", "classroc_1_1fec_1_1OpenfecEncoder.html", null ],
      [ "roc::fec::Parser< PayloadID, Type, Pos >", "classroc_1_1fec_1_1Parser.html", null ],
      [ "roc::fec::Reader", "classroc_1_1fec_1_1Reader.html", null ],
      [ "roc::fec::Writer", "classroc_1_1fec_1_1Writer.html", null ],
      [ "roc::netio::Resolver", "classroc_1_1netio_1_1Resolver.html", null ],
      [ "roc::node::Node", "classroc_1_1node_1_1Node.html", [
        [ "roc::node::Receiver", "classroc_1_1node_1_1Receiver.html", null ],
        [ "roc::node::ReceiverDecoder", "classroc_1_1node_1_1ReceiverDecoder.html", null ],
        [ "roc::node::Sender", "classroc_1_1node_1_1Sender.html", null ],
        [ "roc::node::SenderEncoder", "classroc_1_1node_1_1SenderEncoder.html", null ]
      ] ],
      [ "roc::packet::ConcurrentQueue", "classroc_1_1packet_1_1ConcurrentQueue.html", null ],
      [ "roc::packet::DelayedReader", "classroc_1_1packet_1_1DelayedReader.html", null ],
      [ "roc::packet::Interleaver", "classroc_1_1packet_1_1Interleaver.html", null ],
      [ "roc::packet::PacketFactory", "classroc_1_1packet_1_1PacketFactory.html", null ],
      [ "roc::packet::Queue", "classroc_1_1packet_1_1Queue.html", null ],
      [ "roc::packet::Router", "classroc_1_1packet_1_1Router.html", null ],
      [ "roc::packet::Shipper", "classroc_1_1packet_1_1Shipper.html", null ],
      [ "roc::packet::SortedQueue", "classroc_1_1packet_1_1SortedQueue.html", null ],
      [ "roc::packet::packet_flags_to_str", "classroc_1_1packet_1_1packet__flags__to__str.html", null ],
      [ "roc::pipeline::PipelineLoop", "classroc_1_1pipeline_1_1PipelineLoop.html", [
        [ "roc::pipeline::ReceiverLoop", "classroc_1_1pipeline_1_1ReceiverLoop.html", null ],
        [ "roc::pipeline::SenderLoop", "classroc_1_1pipeline_1_1SenderLoop.html", null ]
      ] ],
      [ "roc::pipeline::ReceiverSessionGroup", "classroc_1_1pipeline_1_1ReceiverSessionGroup.html", null ],
      [ "roc::pipeline::ReceiverSessionRouter", "classroc_1_1pipeline_1_1ReceiverSessionRouter.html", null ],
      [ "roc::pipeline::ReceiverSource", "classroc_1_1pipeline_1_1ReceiverSource.html", null ],
      [ "roc::pipeline::SenderEndpoint", "classroc_1_1pipeline_1_1SenderEndpoint.html", null ],
      [ "roc::pipeline::SenderSession", "classroc_1_1pipeline_1_1SenderSession.html", null ],
      [ "roc::pipeline::SenderSink", "classroc_1_1pipeline_1_1SenderSink.html", null ],
      [ "roc::pipeline::StateTracker", "classroc_1_1pipeline_1_1StateTracker.html", null ],
      [ "roc::pipeline::TranscoderSink", "classroc_1_1pipeline_1_1TranscoderSink.html", null ],
      [ "roc::pipeline::TranscoderSource", "classroc_1_1pipeline_1_1TranscoderSource.html", null ],
      [ "roc::rtcp::Builder", "classroc_1_1rtcp_1_1Builder.html", null ],
      [ "roc::rtcp::Communicator", "classroc_1_1rtcp_1_1Communicator.html", null ],
      [ "roc::rtcp::Composer", "classroc_1_1rtcp_1_1Composer.html", null ],
      [ "roc::rtcp::Parser", "classroc_1_1rtcp_1_1Parser.html", null ],
      [ "roc::rtcp::Reporter", "classroc_1_1rtcp_1_1Reporter.html", null ],
      [ "roc::rtcp::cname_to_str", "classroc_1_1rtcp_1_1cname__to__str.html", null ],
      [ "roc::rtp::Composer", "classroc_1_1rtp_1_1Composer.html", null ],
      [ "roc::rtp::EncodingMap", "classroc_1_1rtp_1_1EncodingMap.html", null ],
      [ "roc::rtp::Filter", "classroc_1_1rtp_1_1Filter.html", null ],
      [ "roc::rtp::Identity", "classroc_1_1rtp_1_1Identity.html", null ],
      [ "roc::rtp::LinkMeter", "classroc_1_1rtp_1_1LinkMeter.html", null ],
      [ "roc::rtp::Parser", "classroc_1_1rtp_1_1Parser.html", null ],
      [ "roc::rtp::Sequencer", "classroc_1_1rtp_1_1Sequencer.html", null ],
      [ "roc::rtp::TimestampExtractor", "classroc_1_1rtp_1_1TimestampExtractor.html", null ],
      [ "roc::rtp::TimestampInjector", "classroc_1_1rtp_1_1TimestampInjector.html", null ],
      [ "roc::sdp::SessionDescription", "classroc_1_1sdp_1_1SessionDescription.html", null ],
      [ "roc::sndio::BackendDispatcher", "classroc_1_1sndio_1_1BackendDispatcher.html", null ],
      [ "roc::sndio::BackendMap", "classroc_1_1sndio_1_1BackendMap.html", null ],
      [ "roc::sndio::PulseaudioBackend", "classroc_1_1sndio_1_1PulseaudioBackend.html", null ],
      [ "roc::sndio::PulseaudioDevice", "classroc_1_1sndio_1_1PulseaudioDevice.html", null ],
      [ "roc::sndio::Pump", "classroc_1_1sndio_1_1Pump.html", null ],
      [ "roc::sndio::SndfileBackend", "classroc_1_1sndio_1_1SndfileBackend.html", null ],
      [ "roc::sndio::SndfileSink", "classroc_1_1sndio_1_1SndfileSink.html", null ],
      [ "roc::sndio::SndfileSource", "classroc_1_1sndio_1_1SndfileSource.html", null ],
      [ "roc::sndio::SoxBackend", "classroc_1_1sndio_1_1SoxBackend.html", null ],
      [ "roc::sndio::SoxSink", "classroc_1_1sndio_1_1SoxSink.html", null ],
      [ "roc::sndio::SoxSource", "classroc_1_1sndio_1_1SoxSource.html", null ],
      [ "roc::sndio::WavBackend", "classroc_1_1sndio_1_1WavBackend.html", null ],
      [ "roc::sndio::WavSink", "classroc_1_1sndio_1_1WavSink.html", null ],
      [ "roc::sndio::WavSource", "classroc_1_1sndio_1_1WavSource.html", null ]
    ] ],
    [ "roc::core::NonCopyable< HashmapNode< void > >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::HashmapNode< Tag >", "classroc_1_1core_1_1HashmapNode.html", null ]
    ] ],
    [ "roc::core::NonCopyable< LimitedPool >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::LimitedPool", "classroc_1_1core_1_1LimitedPool.html", null ]
    ] ],
    [ "roc::core::NonCopyable< ListNode< void > >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::ListNode< Tag >", "classroc_1_1core_1_1ListNode.html", [
        [ "roc::audio::IFrameReader", "classroc_1_1audio_1_1IFrameReader.html", [
          [ "roc::audio::ChannelMapperReader", "classroc_1_1audio_1_1ChannelMapperReader.html", null ],
          [ "roc::audio::Depacketizer", "classroc_1_1audio_1_1Depacketizer.html", null ],
          [ "roc::audio::LatencyMonitor", "classroc_1_1audio_1_1LatencyMonitor.html", null ],
          [ "roc::audio::Mixer", "classroc_1_1audio_1_1Mixer.html", null ],
          [ "roc::audio::PcmMapperReader", "classroc_1_1audio_1_1PcmMapperReader.html", null ],
          [ "roc::audio::ProfilingReader", "classroc_1_1audio_1_1ProfilingReader.html", null ],
          [ "roc::audio::ResamplerReader", "classroc_1_1audio_1_1ResamplerReader.html", null ],
          [ "roc::audio::Watchdog", "classroc_1_1audio_1_1Watchdog.html", null ],
          [ "roc::sndio::ISource", "classroc_1_1sndio_1_1ISource.html", null ]
        ] ],
        [ "roc::audio::IFrameWriter", "classroc_1_1audio_1_1IFrameWriter.html", [
          [ "roc::audio::ChannelMapperWriter", "classroc_1_1audio_1_1ChannelMapperWriter.html", null ],
          [ "roc::audio::Fanout", "classroc_1_1audio_1_1Fanout.html", null ],
          [ "roc::audio::FeedbackMonitor", "classroc_1_1audio_1_1FeedbackMonitor.html", null ],
          [ "roc::audio::NullWriter", "classroc_1_1audio_1_1NullWriter.html", null ],
          [ "roc::audio::Packetizer", "classroc_1_1audio_1_1Packetizer.html", null ],
          [ "roc::audio::PcmMapperWriter", "classroc_1_1audio_1_1PcmMapperWriter.html", null ],
          [ "roc::audio::ProfilingWriter", "classroc_1_1audio_1_1ProfilingWriter.html", null ],
          [ "roc::audio::ResamplerWriter", "classroc_1_1audio_1_1ResamplerWriter.html", null ],
          [ "roc::sndio::ISink", "classroc_1_1sndio_1_1ISink.html", null ]
        ] ],
        [ "roc::ctl::BasicControlEndpoint", "classroc_1_1ctl_1_1BasicControlEndpoint.html", null ],
        [ "roc::ctl::ControlTask", "classroc_1_1ctl_1_1ControlTask.html", [
          [ "roc::ctl::ControlLoop::Tasks::AttachSink", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1AttachSink.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::AttachSource", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1AttachSource.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::BindEndpoint", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1BindEndpoint.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::ConnectEndpoint", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1ConnectEndpoint.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::CreateEndpoint", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1CreateEndpoint.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::DeleteEndpoint", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1DeleteEndpoint.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::DetachSink", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1DetachSink.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::DetachSource", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1DetachSource.html", null ],
          [ "roc::ctl::ControlLoop::Tasks::PipelineProcessing", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks_1_1PipelineProcessing.html", null ]
        ] ],
        [ "roc::netio::BasicPort", "classroc_1_1netio_1_1BasicPort.html", null ],
        [ "roc::packet::Packet", "classroc_1_1packet_1_1Packet.html", null ],
        [ "roc::pipeline::ReceiverEndpoint", "classroc_1_1pipeline_1_1ReceiverEndpoint.html", null ],
        [ "roc::pipeline::ReceiverSession", "classroc_1_1pipeline_1_1ReceiverSession.html", null ],
        [ "roc::pipeline::ReceiverSlot", "classroc_1_1pipeline_1_1ReceiverSlot.html", null ],
        [ "roc::pipeline::SenderSlot", "classroc_1_1pipeline_1_1SenderSlot.html", null ],
        [ "roc::sdp::MediaDescription", "classroc_1_1sdp_1_1MediaDescription.html", null ]
      ] ]
    ] ],
    [ "roc::core::NonCopyable< MpscQueueNode< void > >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::MpscQueueNode< Tag >", "classroc_1_1core_1_1MpscQueueNode.html", [
        [ "roc::ctl::ControlTask", "classroc_1_1ctl_1_1ControlTask.html", null ],
        [ "roc::netio::NetworkTask", "classroc_1_1netio_1_1NetworkTask.html", [
          [ "roc::netio::NetworkLoop::Tasks::AddTcpClientPort", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1AddTcpClientPort.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::AddTcpServerPort", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1AddTcpServerPort.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::AddUdpPort", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1AddUdpPort.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::RemovePort", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1RemovePort.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::ResolveEndpointAddress", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1ResolveEndpointAddress.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::StartUdpRecv", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1StartUdpRecv.html", null ],
          [ "roc::netio::NetworkLoop::Tasks::StartUdpSend", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1StartUdpSend.html", null ]
        ] ],
        [ "roc::packet::Packet", "classroc_1_1packet_1_1Packet.html", null ],
        [ "roc::pipeline::PipelineTask", "classroc_1_1pipeline_1_1PipelineTask.html", [
          [ "roc::pipeline::ReceiverLoop::Task", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Task.html", [
            [ "roc::pipeline::ReceiverLoop::Tasks::AddEndpoint", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Tasks_1_1AddEndpoint.html", null ],
            [ "roc::pipeline::ReceiverLoop::Tasks::CreateSlot", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Tasks_1_1CreateSlot.html", null ],
            [ "roc::pipeline::ReceiverLoop::Tasks::DeleteSlot", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Tasks_1_1DeleteSlot.html", null ],
            [ "roc::pipeline::ReceiverLoop::Tasks::QuerySlot", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Tasks_1_1QuerySlot.html", null ]
          ] ],
          [ "roc::pipeline::SenderLoop::Task", "classroc_1_1pipeline_1_1SenderLoop_1_1Task.html", [
            [ "roc::pipeline::SenderLoop::Tasks::AddEndpoint", "classroc_1_1pipeline_1_1SenderLoop_1_1Tasks_1_1AddEndpoint.html", null ],
            [ "roc::pipeline::SenderLoop::Tasks::CreateSlot", "classroc_1_1pipeline_1_1SenderLoop_1_1Tasks_1_1CreateSlot.html", null ],
            [ "roc::pipeline::SenderLoop::Tasks::DeleteSlot", "classroc_1_1pipeline_1_1SenderLoop_1_1Tasks_1_1DeleteSlot.html", null ],
            [ "roc::pipeline::SenderLoop::Tasks::QuerySlot", "classroc_1_1pipeline_1_1SenderLoop_1_1Tasks_1_1QuerySlot.html", null ]
          ] ]
        ] ]
      ] ]
    ] ],
    [ "roc::core::NonCopyable< RefCounted< T, AllocationPolicy > >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::RefCounted< T, AllocationPolicy >", "classroc_1_1core_1_1RefCounted.html", null ]
    ] ],
    [ "roc::core::NonCopyable< Thread >", "classroc_1_1core_1_1NonCopyable.html", [
      [ "roc::core::Thread", "classroc_1_1core_1_1Thread.html", [
        [ "roc::core::CsvDumper", "classroc_1_1core_1_1CsvDumper.html", null ],
        [ "roc::ctl::ControlTaskQueue", "classroc_1_1ctl_1_1ControlTaskQueue.html", null ],
        [ "roc::netio::NetworkLoop", "classroc_1_1netio_1_1NetworkLoop.html", null ]
      ] ]
    ] ],
    [ "roc::core::NoOwnership< T >", "structroc_1_1core_1_1NoOwnership.html", null ],
    [ "roc::rtcp::header::NtpTimestamp32", "classroc_1_1rtcp_1_1header_1_1NtpTimestamp32.html", null ],
    [ "roc::rtcp::header::NtpTimestamp64", "classroc_1_1rtcp_1_1header_1_1NtpTimestamp64.html", null ],
    [ "roc::rtcp::PacketCounter", "classroc_1_1rtcp_1_1PacketCounter.html", null ],
    [ "roc::rtcp::header::PacketHeader", "classroc_1_1rtcp_1_1header_1_1PacketHeader.html", null ],
    [ "roc::audio::PacketizerMetrics", "structroc_1_1audio_1_1PacketizerMetrics.html", null ],
    [ "roc::rtcp::ParticipantInfo", "structroc_1_1rtcp_1_1ParticipantInfo.html", null ],
    [ "roc::audio::PcmTraits", "structroc_1_1audio_1_1PcmTraits.html", null ],
    [ "roc::pipeline::PipelineLoopConfig", "structroc_1_1pipeline_1_1PipelineLoopConfig.html", null ],
    [ "roc::core::PoolAllocation", "classroc_1_1core_1_1PoolAllocation.html", [
      [ "roc::core::RefCounted< Address, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Route, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Node, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Slot, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Buffer, PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Stream, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< SourceNode, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ],
      [ "roc::core::RefCounted< Packet, core::PoolAllocation >", "classroc_1_1core_1_1RefCounted.html", null ]
    ] ],
    [ "roc::audio::ProfilerConfig", "structroc_1_1audio_1_1ProfilerConfig.html", null ],
    [ "roc::address::ProtocolAttrs", "structroc_1_1address_1_1ProtocolAttrs.html", null ],
    [ "roc::fec::ReaderConfig", "structroc_1_1fec_1_1ReaderConfig.html", null ],
    [ "roc::pipeline::ReceiverCommonConfig", "structroc_1_1pipeline_1_1ReceiverCommonConfig.html", null ],
    [ "roc::pipeline::ReceiverParticipantMetrics", "structroc_1_1pipeline_1_1ReceiverParticipantMetrics.html", null ],
    [ "roc::rtcp::header::ReceiverReportPacket", "classroc_1_1rtcp_1_1header_1_1ReceiverReportPacket.html", null ],
    [ "roc::pipeline::ReceiverSessionConfig", "structroc_1_1pipeline_1_1ReceiverSessionConfig.html", null ],
    [ "roc::pipeline::ReceiverSlotConfig", "structroc_1_1pipeline_1_1ReceiverSlotConfig.html", null ],
    [ "roc::pipeline::ReceiverSlotMetrics", "structroc_1_1pipeline_1_1ReceiverSlotMetrics.html", null ],
    [ "roc::pipeline::ReceiverSourceConfig", "structroc_1_1pipeline_1_1ReceiverSourceConfig.html", null ],
    [ "roc::rtcp::header::ReceptionReportBlock", "classroc_1_1rtcp_1_1header_1_1ReceptionReportBlock.html", null ],
    [ "roc::rtcp::RecvReport", "structroc_1_1rtcp_1_1RecvReport.html", null ],
    [ "roc::core::RefCountedImpl", "classroc_1_1core_1_1RefCountedImpl.html", null ],
    [ "roc::core::RefCountedOwnership< T >", "structroc_1_1core_1_1RefCountedOwnership.html", null ],
    [ "roc::audio::ResamplerConfig", "structroc_1_1audio_1_1ResamplerConfig.html", null ],
    [ "roc::netio::ResolverRequest", "structroc_1_1netio_1_1ResolverRequest.html", null ],
    [ "roc::fec::RS8M_PayloadID", "classroc_1_1fec_1_1RS8M__PayloadID.html", null ],
    [ "roc::packet::RTCP", "structroc_1_1packet_1_1RTCP.html", null ],
    [ "roc::packet::RTP", "structroc_1_1packet_1_1RTP.html", null ],
    [ "roc::rtcp::RttConfig", "structroc_1_1rtcp_1_1RttConfig.html", null ],
    [ "roc::rtcp::RttEstimator", "classroc_1_1rtcp_1_1RttEstimator.html", null ],
    [ "roc::rtcp::RttMetrics", "structroc_1_1rtcp_1_1RttMetrics.html", null ],
    [ "roc::audio::SampleSpec", "classroc_1_1audio_1_1SampleSpec.html", null ],
    [ "roc::rtcp::SdesChunk", "structroc_1_1rtcp_1_1SdesChunk.html", null ],
    [ "roc::rtcp::header::SdesChunkHeader", "classroc_1_1rtcp_1_1header_1_1SdesChunkHeader.html", null ],
    [ "roc::rtcp::SdesItem", "structroc_1_1rtcp_1_1SdesItem.html", null ],
    [ "roc::rtcp::header::SdesItemHeader", "classroc_1_1rtcp_1_1header_1_1SdesItemHeader.html", null ],
    [ "roc::rtcp::header::SdesPacket", "classroc_1_1rtcp_1_1header_1_1SdesPacket.html", null ],
    [ "roc::rtcp::SdesTraverser", "classroc_1_1rtcp_1_1SdesTraverser.html", null ],
    [ "roc::pipeline::SenderParticipantMetrics", "structroc_1_1pipeline_1_1SenderParticipantMetrics.html", null ],
    [ "roc::rtcp::header::SenderReportPacket", "classroc_1_1rtcp_1_1header_1_1SenderReportPacket.html", null ],
    [ "roc::pipeline::SenderSinkConfig", "structroc_1_1pipeline_1_1SenderSinkConfig.html", null ],
    [ "roc::pipeline::SenderSlotConfig", "structroc_1_1pipeline_1_1SenderSlotConfig.html", null ],
    [ "roc::pipeline::SenderSlotMetrics", "structroc_1_1pipeline_1_1SenderSlotMetrics.html", null ],
    [ "roc::rtcp::SendReport", "structroc_1_1rtcp_1_1SendReport.html", null ],
    [ "roc::core::SeqlockImpl", "classroc_1_1core_1_1SeqlockImpl.html", null ],
    [ "roc::core::SharedPtr< T, OwnershipPolicy >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< Buffer >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< Packet >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::audio::IResampler >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::ctl::BasicControlEndpoint >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::netio::BasicPort >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::netio::IConnHandler >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::node::Context >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::SharedPtr< roc::pipeline::ReceiverSession >", "classroc_1_1core_1_1SharedPtr.html", null ],
    [ "roc::core::Slice< T >", "classroc_1_1core_1_1Slice.html", null ],
    [ "roc::core::Slice< audio::sample_t >", "classroc_1_1core_1_1Slice.html", null ],
    [ "roc::core::Slice< sample_t >", "classroc_1_1core_1_1Slice.html", null ],
    [ "roc::core::Slice< uint8_t >", "classroc_1_1core_1_1Slice.html", null ],
    [ "roc::core::SlabPoolImpl::SlotHeader", "structroc_1_1core_1_1SlabPoolImpl_1_1SlotHeader.html", null ],
    [ "roc::address::SocketAddr", "classroc_1_1address_1_1SocketAddr.html", null ],
    [ "roc::netio::SocketOpts", "structroc_1_1netio_1_1SocketOpts.html", null ],
    [ "roc::pipeline::PipelineLoop::Stats", "structroc_1_1pipeline_1_1PipelineLoop_1_1Stats.html", null ],
    [ "roc::ctl::ControlLoop::Tasks", "classroc_1_1ctl_1_1ControlLoop_1_1Tasks.html", null ],
    [ "roc::netio::NetworkLoop::Tasks", "classroc_1_1netio_1_1NetworkLoop_1_1Tasks.html", null ],
    [ "roc::pipeline::ReceiverLoop::Tasks", "classroc_1_1pipeline_1_1ReceiverLoop_1_1Tasks.html", null ],
    [ "roc::pipeline::SenderLoop::Tasks", "classroc_1_1pipeline_1_1SenderLoop_1_1Tasks.html", null ],
    [ "roc::netio::TcpConnectionConfig", "structroc_1_1netio_1_1TcpConnectionConfig.html", [
      [ "roc::netio::TcpClientConfig", "structroc_1_1netio_1_1TcpClientConfig.html", null ],
      [ "roc::netio::TcpServerConfig", "structroc_1_1netio_1_1TcpServerConfig.html", null ]
    ] ],
    [ "roc::pipeline::TranscoderConfig", "structroc_1_1pipeline_1_1TranscoderConfig.html", null ],
    [ "roc::rtcp::Traverser", "classroc_1_1rtcp_1_1Traverser.html", null ],
    [ "roc::packet::UDP", "structroc_1_1packet_1_1UDP.html", null ],
    [ "roc::netio::UdpConfig", "structroc_1_1netio_1_1UdpConfig.html", null ],
    [ "roc::audio::WatchdogConfig", "structroc_1_1audio_1_1WatchdogConfig.html", null ],
    [ "roc::sndio::WavHeader", "classroc_1_1sndio_1_1WavHeader.html", null ],
    [ "roc::sndio::WavHeader::WavHeaderData", "structroc_1_1sndio_1_1WavHeader_1_1WavHeaderData.html", null ],
    [ "roc::fec::WriterConfig", "structroc_1_1fec_1_1WriterConfig.html", null ],
    [ "roc::rtcp::header::XrBlockHeader", "classroc_1_1rtcp_1_1header_1_1XrBlockHeader.html", null ],
    [ "roc::rtcp::header::XrDelayMetricsBlock", "classroc_1_1rtcp_1_1header_1_1XrDelayMetricsBlock.html", null ],
    [ "roc::rtcp::header::XrDlrrBlock", "classroc_1_1rtcp_1_1header_1_1XrDlrrBlock.html", null ],
    [ "roc::rtcp::header::XrDlrrSubblock", "classroc_1_1rtcp_1_1header_1_1XrDlrrSubblock.html", null ],
    [ "roc::rtcp::header::XrMeasurementInfoBlock", "classroc_1_1rtcp_1_1header_1_1XrMeasurementInfoBlock.html", null ],
    [ "roc::rtcp::header::XrPacket", "classroc_1_1rtcp_1_1header_1_1XrPacket.html", null ],
    [ "roc::rtcp::header::XrQueueMetricsBlock", "classroc_1_1rtcp_1_1header_1_1XrQueueMetricsBlock.html", null ],
    [ "roc::rtcp::header::XrRrtrBlock", "classroc_1_1rtcp_1_1header_1_1XrRrtrBlock.html", null ],
    [ "roc::rtcp::XrTraverser", "classroc_1_1rtcp_1_1XrTraverser.html", null ]
];