var searchData=
[
  ['ratelimiter_2147',['RateLimiter',['../classroc_1_1core_1_1RateLimiter.html',1,'roc::core']]],
  ['reader_2148',['Reader',['../classroc_1_1fec_1_1Reader.html',1,'roc::fec']]],
  ['readerconfig_2149',['ReaderConfig',['../structroc_1_1fec_1_1ReaderConfig.html',1,'roc::fec']]],
  ['receiver_2150',['Receiver',['../classroc_1_1node_1_1Receiver.html',1,'roc::node']]],
  ['receivercommonconfig_2151',['ReceiverCommonConfig',['../structroc_1_1pipeline_1_1ReceiverCommonConfig.html',1,'roc::pipeline']]],
  ['receiverconfig_2152',['ReceiverConfig',['../structroc_1_1pipeline_1_1ReceiverConfig.html',1,'roc::pipeline']]],
  ['receiverdecoder_2153',['ReceiverDecoder',['../classroc_1_1node_1_1ReceiverDecoder.html',1,'roc::node']]],
  ['receiverendpoint_2154',['ReceiverEndpoint',['../classroc_1_1pipeline_1_1ReceiverEndpoint.html',1,'roc::pipeline']]],
  ['receiverloop_2155',['ReceiverLoop',['../classroc_1_1pipeline_1_1ReceiverLoop.html',1,'roc::pipeline']]],
  ['receiverreportpacket_2156',['ReceiverReportPacket',['../classroc_1_1rtcp_1_1header_1_1ReceiverReportPacket.html',1,'roc::rtcp::header']]],
  ['receiversession_2157',['ReceiverSession',['../classroc_1_1pipeline_1_1ReceiverSession.html',1,'roc::pipeline']]],
  ['receiversessionconfig_2158',['ReceiverSessionConfig',['../structroc_1_1pipeline_1_1ReceiverSessionConfig.html',1,'roc::pipeline']]],
  ['receiversessiongroup_2159',['ReceiverSessionGroup',['../classroc_1_1pipeline_1_1ReceiverSessionGroup.html',1,'roc::pipeline']]],
  ['receiversessionmetrics_2160',['ReceiverSessionMetrics',['../structroc_1_1pipeline_1_1ReceiverSessionMetrics.html',1,'roc::pipeline']]],
  ['receiverslot_2161',['ReceiverSlot',['../classroc_1_1pipeline_1_1ReceiverSlot.html',1,'roc::pipeline']]],
  ['receiverslotmetrics_2162',['ReceiverSlotMetrics',['../structroc_1_1pipeline_1_1ReceiverSlotMetrics.html',1,'roc::pipeline']]],
  ['receiversource_2163',['ReceiverSource',['../classroc_1_1pipeline_1_1ReceiverSource.html',1,'roc::pipeline']]],
  ['receiverstate_2164',['ReceiverState',['../classroc_1_1pipeline_1_1ReceiverState.html',1,'roc::pipeline']]],
  ['receptionmetrics_2165',['ReceptionMetrics',['../structroc_1_1rtcp_1_1ReceptionMetrics.html',1,'roc::rtcp']]],
  ['receptionreportblock_2166',['ReceptionReportBlock',['../classroc_1_1rtcp_1_1header_1_1ReceptionReportBlock.html',1,'roc::rtcp::header']]],
  ['refcounted_2167',['RefCounted',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20basiccontrolendpoint_2c_20core_3a_3aarenaallocation_20_3e_2168',['RefCounted&lt; BasicControlEndpoint, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20basicport_2c_20core_3a_3aarenaallocation_20_3e_2169',['RefCounted&lt; BasicPort, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20buffer_3c_20t_20_3e_2c_20poolallocation_20_3e_2170',['RefCounted&lt; Buffer&lt; T &gt;, PoolAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20context_2c_20core_3a_3amanualallocation_20_3e_2171',['RefCounted&lt; Context, core::ManualAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20iconnhandler_2c_20core_3a_3amanualallocation_20_3e_2172',['RefCounted&lt; IConnHandler, core::ManualAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20iresampler_2c_20core_3a_3aarenaallocation_20_3e_2173',['RefCounted&lt; IResampler, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20mediadescription_2c_20core_3a_3aarenaallocation_20_3e_2174',['RefCounted&lt; MediaDescription, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20node_2c_20core_3a_3apoolallocation_20_3e_2175',['RefCounted&lt; Node, core::PoolAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20packet_2c_20core_3a_3apoolallocation_20_3e_2176',['RefCounted&lt; Packet, core::PoolAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20receiverendpoint_2c_20core_3a_3aarenaallocation_20_3e_2177',['RefCounted&lt; ReceiverEndpoint, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20receiversession_2c_20core_3a_3aarenaallocation_20_3e_2178',['RefCounted&lt; ReceiverSession, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20receiverslot_2c_20core_3a_3aarenaallocation_20_3e_2179',['RefCounted&lt; ReceiverSlot, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20senderslot_2c_20core_3a_3aarenaallocation_20_3e_2180',['RefCounted&lt; SenderSlot, core::ArenaAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcounted_3c_20slot_2c_20core_3a_3apoolallocation_20_3e_2181',['RefCounted&lt; Slot, core::PoolAllocation &gt;',['../classroc_1_1core_1_1RefCounted.html',1,'roc::core']]],
  ['refcountedimpl_2182',['RefCountedImpl',['../classroc_1_1core_1_1RefCountedImpl.html',1,'roc::core']]],
  ['refcountedownership_2183',['RefCountedOwnership',['../structroc_1_1core_1_1RefCountedOwnership.html',1,'roc::core']]],
  ['removeport_2184',['RemovePort',['../classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1RemovePort.html',1,'roc::netio::NetworkLoop::Tasks']]],
  ['resamplermap_2185',['ResamplerMap',['../classroc_1_1audio_1_1ResamplerMap.html',1,'roc::audio']]],
  ['resamplerreader_2186',['ResamplerReader',['../classroc_1_1audio_1_1ResamplerReader.html',1,'roc::audio']]],
  ['resamplerwriter_2187',['ResamplerWriter',['../classroc_1_1audio_1_1ResamplerWriter.html',1,'roc::audio']]],
  ['resolveendpointaddress_2188',['ResolveEndpointAddress',['../classroc_1_1netio_1_1NetworkLoop_1_1Tasks_1_1ResolveEndpointAddress.html',1,'roc::netio::NetworkLoop::Tasks']]],
  ['resolver_2189',['Resolver',['../classroc_1_1netio_1_1Resolver.html',1,'roc::netio']]],
  ['resolverrequest_2190',['ResolverRequest',['../structroc_1_1netio_1_1ResolverRequest.html',1,'roc::netio']]],
  ['router_2191',['Router',['../classroc_1_1packet_1_1Router.html',1,'roc::packet']]],
  ['rs8m_5fpayloadid_2192',['RS8M_PayloadID',['../classroc_1_1fec_1_1RS8M__PayloadID.html',1,'roc::fec']]],
  ['rtcp_2193',['RTCP',['../structroc_1_1packet_1_1RTCP.html',1,'roc::packet']]],
  ['rtp_2194',['RTP',['../structroc_1_1packet_1_1RTP.html',1,'roc::packet']]]
];
