name: "build"

on:
  push:
    branches:
      - source

  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    outputs:
      deployment-page-url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    permissions:
      pages: write
      id-token: write

    needs: build
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.deployment-page-url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
