name: "build"

on:
  push:
    branches:
      - source

  repository_dispatch:
    types:
      - trigger_build

  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www
        uses: actions/checkout@v4

      - name: Checkout roc-toolkit
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/roc-toolkit
          path: roc-toolkit

      - name: Checkout rocd
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/rocd
          path: rocd

      - name: Checkout roc-droid
        uses: actions/checkout@v4
        with:
          repository: roc-streaming/roc-droid
          path: roc-droid
          ref: flutter

      - name: Build roc-toolkit documentation
        run: |
          ./roc-toolkit/scripts/make_doc.sh
          cp -av roc-toolkit/docs/html www/toolkit

      - name: Build rocd documentation
        run: |
          make -C rocd docs-docker
          cp -av rocd/site www/daemom

      - name: Build roc-droid documentation
        run: |
          ./roc-droid/script/generate_docs.py
          cp -av roc-droid/site www/droid

      - name: Publish web-site
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: content
          folder: www
          single-commit: true
